creation_rules:
  # Encrypt any file matching secrets.*.yaml or *.enc.yaml
  - path_regex: '(secrets\..*\.yaml|.*\.enc\.yaml)$'
    age: age1f4tdre7g7nnqz9grdmvksn8zjan3fdyj6y87wz87fk0ru5dysa0s09v7dm

  # Encrypt .env files
  - path_regex: '\.env\.enc$'
    age: age1f4tdre7g7nnqz9grdmvksn8zjan3fdyj6y87wz87fk0ru5dysa0s09v7dm
