# Synthesis target: ising_sampler_v2.v (synchronous p-bit, ~50% area reduction)
# Generated by Carnot Exp 636. Replace synth_ising.tcl with this file.
# Run: vivado -mode batch -source hardware/kv260/synth_ising_v2.tcl
#
# synth_ising_v2.tcl — Vivado batch-mode synthesis script for ising_sampler_v2.v
#
# Researcher summary:
#   Synthesizes the 128-spin synchronous p-bit Ising sampler RTL targeting the
#   KV260 (xck26) and generates a bitfile at output/carnot_ising_synth_v2/carnot_ising_v2.bit.
#   v2 replaces the asynchronous sequential sub-FSM of v1 with a synchronous
#   checkerboard update, eliminating the DAC and random-spin-selection LFSR mux.
#   Expected area reduction: ~50% fewer LUTs vs v1 (arXiv 2604.01564).
#
# Detailed explanation for engineers:
#   This script was updated by Exp 636 to target ising_sampler_v2.v (module
#   ising_sampler_128_sync) instead of ising_sampler_v1.v (module ising_sampler_128).
#   The key changes from synth_ising.tcl:
#     1. rtl_files now lists hardware/kv260/ising_sampler_v2.v
#     2. top_module is now ising_sampler_128_sync (v2 renamed the module)
#     3. output_dir is output/carnot_ising_synth_v2 (separate from v1 outputs)
#     4. bitfile written as carnot_ising_v2.bit
#
#   Invoke via:
#     vivado -mode batch -source hardware/kv260/synth_ising_v2.tcl
#
#   Prerequisites:
#     - Vivado 2023.x or later installed and on PATH
#     - KV260 board files installed (xck26-sfvc784-2LV-c)
#     - This script run from the repository root
#
# Target: xck26-sfvc784-2LV-c (KV260 production SOM)
# Expected build time: ~15-30 minutes on a 16-core host

set part "xck26-sfvc784-2LV-c"
set top_module "ising_sampler_128_sync"
set rtl_files [list \
    "hardware/kv260/ising_sampler_v2.v" \
]
set output_dir "output/carnot_ising_synth_v2"

# Create output directory
file mkdir $output_dir

# Create in-memory project
create_project -in_memory -part $part

# Add RTL sources
add_files $rtl_files
set_property top $top_module [current_fileset]

# Synthesis step
synth_design -top $top_module -part $part -flatten_hierarchy rebuilt

# Write post-synthesis checkpoint
write_checkpoint -force ${output_dir}/post_synth.dcp

# Implementation (place and route)
opt_design
place_design
route_design

# Write bitfile
write_bitstream -force ${output_dir}/carnot_ising_v2.bit

# Report resource utilization
report_utilization -file ${output_dir}/utilization.rpt
report_timing_summary -file ${output_dir}/timing.rpt

puts "Synthesis complete: ${output_dir}/carnot_ising_v2.bit"
puts "Set CARNOT_KV260_BITFILE=${output_dir}/carnot_ising_v2.bit before running hardware tests"
