# synth_ising.tcl — Vivado batch-mode synthesis script for ising_sampler_v1.v
#
# Researcher summary:
#   Synthesizes the 128-spin Ising sampler RTL targeting the KV260 (xck26)
#   and generates a bitfile at output/carnot_ising.bit.
#
# Detailed explanation for engineers:
#   This stub was auto-generated by Exp 568 when CARNOT_KV260_BITFILE was
#   not set. Invoke via:
#     vivado -mode batch -source hardware/kv260/synth_ising.tcl
#
#   Prerequisites:
#     - Vivado 2023.x or later installed and on PATH
#     - KV260 board files installed (xck26-sfvc784-2LV-c)
#     - This script run from the repository root
#
# Target: xck26-sfvc784-2LV-c (KV260 production SOM)
# Expected build time: ~15-30 minutes on a 16-core host

set part "xck26-sfvc784-2LV-c"
set top_module "ising_sampler_128"
set rtl_files [list \
    "hardware/kv260/ising_sampler_v1.v" \
]
set output_dir "output/carnot_ising_synth"

# Create output directory
file mkdir $output_dir

# Create in-memory project
create_project -in_memory -part $part

# Add RTL sources
add_files $rtl_files
set_property top $top_module [current_fileset]

# Synthesis step
synth_design -top $top_module -part $part -flatten_hierarchy rebuilt

# Write post-synthesis checkpoint
write_checkpoint -force ${output_dir}/post_synth.dcp

# Implementation (place and route)
opt_design
place_design
route_design

# Write bitfile
write_bitstream -force ${output_dir}/carnot_ising.bit

# Report resource utilization
report_utilization -file ${output_dir}/utilization.rpt
report_timing_summary -file ${output_dir}/timing.rpt

puts "Synthesis complete: ${output_dir}/carnot_ising.bit"
puts "Set CARNOT_KV260_BITFILE=${output_dir}/carnot_ising.bit before running Exp 568"
