"""Lean 4 formal verification bridge for Sudoku constraint satisfaction.

**Researcher summary:**
    Translates Sudoku solutions into Lean 4 propositions and verifies them via
    the Lean4VerifierBackend subprocess bridge. Enables formally-checked solve
    rate measurement for expert Sudoku puzzles.

**Detailed explanation for engineers:**
    This module bridges two existing components:
    1. The Sudoku energy model (`carnot.verify.sudoku`) which encodes Sudoku
       rules as differentiable JAX energy terms.
    2. The Lean 4 subprocess verifier (`carnot.verify.lean4_bridge`) which
       calls the `lean` binary to formally check typed propositions.

    The integration works as follows:
    - Given a proposed 9x9 Sudoku solution, `encode_sudoku_solution_as_lean4`
      generates a complete Lean 4 source file that:
        a. Defines the solution as a flat list of 81 `Nat` values.
        b. Defines helper functions for row/column/box uniqueness checking.
        c. Asserts that given clue digits match the proposed values.
        d. Uses `#eval` to trigger verification at load time.
    - `SudokuLean4Verifier.verify_solution` passes this Lean code directly to
      `Lean4VerifierBackend.verify()`, which writes it to a temp file and
      invokes `lean`. If lean exits with 0, the solution is formally verified.

    **Why Lean 4 instead of just the EBM?**
    The EBM (energy-based model) check is approximate: it uses floating-point
    arithmetic and a satisfaction threshold (0.01) to decide if constraints
    pass. Lean 4 provides a formally-certified check: the type system enforces
    proof obligations, and `decide` tactics compile decidable propositions into
    verified machine code. This is a stronger guarantee than gradient-based
    energy minimization.

    **When lean is not installed:**
    `Lean4VerifierBackend.verify()` returns `float('inf')` when the `lean`
    binary is not found (FileNotFoundError). In that case, `verify_solution`
    returns False for every input. The `lean4_available()` method lets callers
    detect this state upfront and fall back gracefully.

Spec: REQ-VERIFY-1740, SCENARIO-VERIFY-1740
"""

from __future__ import annotations

import subprocess

from carnot.verify.lean4_bridge import Lean4VerifierBackend


def encode_sudoku_solution_as_lean4(
    clues: list[list[int]],
    solution: list[list[int]],
) -> str:
    """Generate Lean 4 source code that formally verifies a Sudoku solution.

    **Detailed explanation for engineers:**
        Produces a self-contained Lean 4 file that:
        1. Defines the proposed 9x9 solution as a flat 81-element `List Nat`.
        2. Defines `allDistinct` using `List.eraseDups` (standard Lean 4
           library — removes duplicates by reference equality on `Nat`).
        3. Defines `getRow`, `getCol`, `getBox` to slice out the 9 relevant
           cells for each structural group.
        4. Defines `structureValid`: all 27 groups (9 rows + 9 cols + 9 boxes)
           must be all-distinct.
        5. Defines `cluesValid`: each pre-filled cell index must match the
           given clue digit.
        6. Ends with `#eval isSudokuValid solution` — when lean processes this
           file without error, it evaluates the expression and prints `true`.
           A non-zero exit code (or false evaluation) signals verification
           failure.

    Args:
        clues: 9x9 grid of given digits (0 = empty cell, 1-9 = given digit).
        solution: 9x9 grid of proposed digits (1-9 for every cell).

    Returns:
        Complete Lean 4 source code as a UTF-8 string.

    Spec: REQ-VERIFY-1740, SCENARIO-VERIFY-1740
    """
    # Flatten solution to 81 comma-separated Nat literals for the Lean list
    flat_values = [str(solution[r][c]) for r in range(9) for c in range(9)]
    solution_list = ", ".join(flat_values)

    # Build clue-validity checks: one equality per pre-filled cell
    # Each line checks that the cell at flat index (r*9+c) equals the clue
    clue_lines: list[str] = []
    for r in range(9):
        for c in range(9):
            if clues[r][c] != 0:
                idx = r * 9 + c
                val = clues[r][c]
                clue_lines.append(f"  grid.get! {idx} == {val}")

    # If there are no clues (bare solution), trivially true
    if clue_lines:
        clues_body = " &&\n".join(clue_lines)
    else:
        clues_body = "  true"

    return f"""\
-- Sudoku solution verification
-- Auto-generated by carnot.verify.sudoku_lean4
-- Spec: REQ-VERIFY-1740, SCENARIO-VERIFY-1740

-- Proposed solution as a flat row-major list of 81 digits (1-9)
def solution : List Nat := [{solution_list}]

-- allDistinct: true iff every element in the list appears exactly once.
-- Uses List.eraseDups which removes duplicate Nat values by equality.
def allDistinct (l : List Nat) : Bool :=
  l.eraseDups.length == l.length

-- getRow: extract the 9 values in row r (0-indexed) from the flat grid.
def getRow (grid : List Nat) (r : Nat) : List Nat :=
  (List.range 9).map (fun c => grid.get! (r * 9 + c))

-- getCol: extract the 9 values in column c (0-indexed) from the flat grid.
def getCol (grid : List Nat) (c : Nat) : List Nat :=
  (List.range 9).map (fun r => grid.get! (r * 9 + c))

-- getBox: extract the 9 values in 3x3 box b (0-indexed, reading order).
-- Box 0=top-left, 1=top-middle, ..., 8=bottom-right.
def getBox (grid : List Nat) (b : Nat) : List Nat :=
  let br := (b / 3) * 3
  let bc := (b % 3) * 3
  (List.range 9).map (fun k =>
    grid.get! ((br + k / 3) * 9 + (bc + k % 3)))

-- structureValid: all 9 rows, 9 columns, and 9 boxes contain distinct digits.
def structureValid (grid : List Nat) : Bool :=
  (List.range 9).all (fun r => allDistinct (getRow grid r)) &&
  (List.range 9).all (fun c => allDistinct (getCol grid c)) &&
  (List.range 9).all (fun b => allDistinct (getBox grid b))

-- cluesValid: every pre-filled cell must still hold its given digit.
def cluesValid (grid : List Nat) : Bool :=
{clues_body}

-- isSudokuValid: structure is correct AND all clues are respected.
def isSudokuValid (grid : List Nat) : Bool :=
  structureValid grid && cluesValid grid

-- Trigger formal evaluation: lean exits 0 only if this evaluates to `true`.
#eval isSudokuValid solution
"""


class SudokuLean4Verifier:
    """Integrates the Sudoku constraint model with Lean 4 formal verification.

    **Researcher summary:**
        Wraps `Lean4VerifierBackend` to formally verify Sudoku solutions.
        `lean4_available()` checks if lean is on the PATH; `verify_solution`
        generates Lean 4 code and runs it through the backend.

    **Detailed explanation for engineers:**
        This class is the integration point between:
        - `encode_sudoku_solution_as_lean4()` which produces verifiable Lean 4
        - `Lean4VerifierBackend` which invokes the lean subprocess

        Typical use:
            verifier = SudokuLean4Verifier()
            if verifier.lean4_available():
                is_valid = verifier.verify_solution(clues, solution)
            else:
                # Fall back to EBM constraint check
                ...

    Spec: REQ-VERIFY-1740, SCENARIO-VERIFY-1740
    """

    def __init__(self, backend: Lean4VerifierBackend | None = None) -> None:
        """Create a verifier using the given backend, or a default one.

        Args:
            backend: Lean4VerifierBackend instance to use. If None, creates a
                default backend with 30-second timeout (lean type-checking a
                medium-complexity file can take a few seconds on first run).
        """
        # 30-second timeout: lean may need to compile standard library stubs
        # on first invocation; 5 seconds is too tight for that scenario.
        self._backend = backend or Lean4VerifierBackend(timeout_seconds=30.0)

    def lean4_available(self) -> bool:
        """Return True if the lean binary is on the PATH and responds to --version.

        **Detailed explanation for engineers:**
            Runs `lean --version` with a 5-second timeout. This is a lightweight
            probe that only checks availability without invoking the type checker.
            We use the backend's configured `lean_path` so that tests can inject
            a custom path.
        """
        try:
            result = subprocess.run(
                [self._backend.lean_path, "--version"],
                capture_output=True,
                text=True,
                timeout=5.0,
                check=False,
            )
            return result.returncode == 0
        except (FileNotFoundError, subprocess.TimeoutExpired):
            return False

    def verify_solution(
        self,
        clues: list[list[int]],
        solution: list[list[int]],
    ) -> bool:
        """Formally verify a proposed Sudoku solution using Lean 4.

        **Detailed explanation for engineers:**
            1. Generates the Lean 4 verification program via
               `encode_sudoku_solution_as_lean4`.
            2. Passes the full program to `Lean4VerifierBackend.verify()`,
               which writes it to a temp `.lean` file and runs `lean`.
            3. Returns True iff lean exits with code 0 (formal verification
               succeeded — the solution is provably valid).
            4. Returns False on lean error, timeout, or FileNotFoundError.

        Args:
            clues: 9x9 grid of given digits (0 = empty, 1-9 = clue digit).
            solution: Proposed 9x9 complete solution (all cells filled 1-9).

        Returns:
            True if lean formally verified the solution, False otherwise.
        """
        lean_code = encode_sudoku_solution_as_lean4(clues, solution)
        energy = self._backend.verify(lean_code)
        # Binary energy model: 0.0 = verified, float('inf') = failed/unavailable
        return energy == 0.0
