#!/usr/bin/env bash
# Cloud GPU setup script — generated by Exp 404 (RETRO-022 / REQ-INFRA-020)
# Run the section for your preferred cloud provider.
# Estimated cost: $1.10/hr (A100 80GB)
#
# IMPORTANT: Authenticate with your chosen provider CLI before running.

# -----------------------------------------------------------------------
# Option 1: Lambda Labs
# Install: pip install lambdalabs-cli
# Auth:    lambdalabs auth login
# -----------------------------------------------------------------------
lambdalabs instance create --instance-type gpu_1x_a100 --region us-west-2 --quantity 1

# -----------------------------------------------------------------------
# Option 2: vast.ai
# Install: pip install vastai
# Auth:    vastai set api-key <YOUR_API_KEY>
# Find ID: vastai search offers 'gpu_name=A100' --storage 50
# Replace <id> below with the offer ID from the search above.
# -----------------------------------------------------------------------
vastai create instance <id> --image pytorch/pytorch:2.3.0-cuda12.1

# -----------------------------------------------------------------------
# Option 3: RunPod
# Install: https://docs.runpod.io/cli/install-runpodctl
# Auth:    runpodctl config --apiKey <YOUR_API_KEY>
# -----------------------------------------------------------------------
runpodctl create pod --gpuType NVIDIA_A100_80GB
