"""Sandboxed hypothesis execution environment.

**Researcher summary:**
    Executes untrusted hypothesis code in an isolated namespace with static
    import analysis, timeout enforcement (SIGALRM), and captured I/O. Part
    of the autoresearch self-improvement pipeline.

**Detailed explanation for engineers:**
    The autoresearch pipeline lets Carnot autonomously generate and test
    hypotheses about better EBM architectures, training methods, or sampling
    strategies. This module provides the "sandbox" where hypothesis code runs.

    **The self-improvement pipeline (big picture):**
    1. An LLM (e.g., Qwen3, Claude) generates a hypothesis as Python code
    2. This sandbox executes the code safely (with import restrictions, timeouts)
    3. The evaluator (evaluator.py) compares results against baselines
    4. If the hypothesis improves on baselines, it may be adopted

    **Why sandboxing?**
    Since hypothesis code is generated by an LLM, it could contain anything:
    - Malicious imports (os.system, subprocess, socket)
    - Infinite loops (timeout protection)
    - Excessive memory usage (advisory tracking)
    - Syntax errors or runtime crashes

    The sandbox provides multiple layers of protection:
    1. **Static analysis**: Parses the AST to detect blocked imports BEFORE execution
    2. **Timeout**: Uses Unix SIGALRM to kill long-running hypotheses
    3. **Namespace isolation**: Code runs in a fresh dict, not the global namespace
    4. **I/O capture**: stdout/stderr are captured for logging

    **Contract for hypothesis code:**
    The hypothesis must define a ``run(benchmark_data: dict) -> dict`` function.
    The returned dict contains metrics (e.g., final_energy, wall_clock_seconds)
    that the evaluator uses to compare against baselines.

Executes hypothesis code in isolation with:
- Hard timeout
- Memory limit (tracked, not enforced at OS level -- use containers for hard limits)
- Import whitelist enforcement
- Read-only data access
- Captured stdout/stderr and metrics

Spec: REQ-AUTO-004, REQ-AUTO-009
"""

from __future__ import annotations

import ast
import io
import json
import signal
import sys
import time
import traceback
from contextlib import redirect_stderr, redirect_stdout
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any


# Modules that hypotheses are NOT allowed to import.
# These provide filesystem access, network access, process spawning, or other
# capabilities that untrusted code should never have.
BLOCKED_MODULES = frozenset({
    "os",            # filesystem operations, environment variables
    "subprocess",    # spawning external processes
    "socket",        # raw network access
    "shutil",        # file/directory operations (copy, move, delete)
    "ctypes",        # foreign function interface (can call arbitrary C code)
    "multiprocessing",  # spawning processes
    "threading",     # spawning threads (could bypass timeout)
    "http",          # HTTP server/client
    "urllib",        # URL handling and network requests
    "requests",      # popular HTTP library
    "pathlib",       # filesystem path operations
    "tempfile",      # temporary file creation
    "signal",        # signal handling (could disable our timeout)
    "importlib",     # dynamic imports (could bypass our blocklist)
})


@dataclass
class SandboxConfig:
    """Configuration for the sandbox execution environment.

    **Researcher summary:**
        Timeout, memory cap, and import blocklist for hypothesis execution.

    **Detailed explanation for engineers:**
        Controls the safety parameters for running untrusted hypothesis code.

    Attributes:
        timeout_seconds: Maximum wall-clock time for hypothesis execution.
            Default 1800 (30 minutes). After this, a SIGALRM kills the
            execution and the result is marked as timed_out.
        max_memory_mb: Advisory memory limit in megabytes. Default 16384
            (16 GB). Currently tracked but NOT enforced at the OS level —
            for hard enforcement, run in a container with cgroup limits.
        blocked_modules: Frozenset of module names that cannot be imported.
            The static analyzer checks for these before execution begins.

    Spec: REQ-AUTO-004
    """

    timeout_seconds: int = 1800  # 30 minutes
    max_memory_mb: int = 16384  # 16GB (advisory)
    blocked_modules: frozenset[str] = BLOCKED_MODULES


@dataclass
class SandboxResult:
    """Result of a sandboxed hypothesis execution.

    **Researcher summary:**
        Contains success/failure, metrics dict, captured I/O, timing, and
        timeout flag. Fed into the evaluator for three-gate assessment.

    **Detailed explanation for engineers:**
        After running hypothesis code, this dataclass captures everything
        needed for evaluation:
        - ``success``: Did the code run without errors and return a dict?
        - ``metrics``: The dict returned by the hypothesis's ``run()`` function.
          Typically contains keys like "final_energy", "wall_clock_seconds",
          "peak_memory_mb" for each benchmark.
        - ``stdout``/``stderr``: Captured print output (useful for debugging).
        - ``error``: Error message if the hypothesis failed.
        - ``wall_clock_seconds``: Total execution time.
        - ``timed_out``: True if the hypothesis hit the timeout limit.

    Spec: REQ-AUTO-004, REQ-AUTO-008
    """

    success: bool
    metrics: dict[str, Any] = field(default_factory=dict)
    stdout: str = ""
    stderr: str = ""
    error: str | None = None
    wall_clock_seconds: float = 0.0
    timed_out: bool = False


def check_imports(code: str, blocked: frozenset[str]) -> list[str]:
    """Check hypothesis code for blocked imports using AST analysis.

    **Researcher summary:**
        Static analysis: parses code into an AST and walks it to find
        ``import X`` or ``from X import ...`` where X is in the blocklist.

    **Detailed explanation for engineers:**
        Before executing any hypothesis code, we parse it into an Abstract
        Syntax Tree (AST) and scan for import statements. This catches
        blocked imports BEFORE execution, which is safer than trying to
        intercept them at runtime.

        The check handles both forms of Python imports:
        - ``import os`` (ast.Import node)
        - ``from os.path import join`` (ast.ImportFrom node)

        For dotted imports like ``import os.path``, we check the root
        module ("os") against the blocklist.

        If the code has a syntax error and cannot be parsed, we return
        a special violation string indicating we cannot verify safety.

    Args:
        code: Python source code as a string.
        blocked: Frozenset of blocked module root names.

    Returns:
        List of blocked module names found. Empty list means no violations.

    For example::

        violations = check_imports("import os\\nimport jax", BLOCKED_MODULES)
        assert violations == ["os"]

    Spec: REQ-AUTO-009
    """
    violations: list[str] = []
    try:
        tree = ast.parse(code)
    except SyntaxError:
        # Cannot parse = cannot verify safety. Flag it.
        return ["<syntax error — cannot check imports>"]

    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            # Handles: import os, import os.path, import os as operating_system
            for alias in node.names:
                root = alias.name.split(".")[0]  # "os.path" -> "os"
                if root in blocked:
                    violations.append(root)
        elif isinstance(node, ast.ImportFrom):
            # Handles: from os import getcwd, from os.path import join
            if node.module:
                root = node.module.split(".")[0]  # "os.path" -> "os"
                if root in blocked:
                    violations.append(root)
    return violations


def run_in_sandbox(
    hypothesis_code: str,
    benchmark_data: dict[str, Any],
    config: SandboxConfig | None = None,
) -> SandboxResult:
    """Execute hypothesis code in a sandboxed environment.

    **Researcher summary:**
        Static import check -> isolated exec with timeout -> call run() ->
        return SandboxResult with metrics or error.

    **Detailed explanation for engineers:**
        This is the main entry point for the sandbox. It:

        1. **Static analysis**: Calls ``check_imports()`` to scan for blocked
           modules. If any are found, immediately returns a FAIL result
           without executing anything.

        2. **Execution**: Compiles the hypothesis code and runs it in an
           isolated namespace (a fresh dict with only ``__builtins__``).
           stdout and stderr are captured via ``contextlib.redirect_*``.

        3. **Timeout**: Sets a Unix SIGALRM timer. If the hypothesis runs
           longer than ``config.timeout_seconds``, a TimeoutError is raised
           and caught. Note: SIGALRM only works on Unix systems.

        4. **Calling run()**: After executing the hypothesis code (which
           defines functions/classes), we look for a ``run`` function in
           the namespace and call it with ``benchmark_data``. The ``run``
           function must return a dict of metrics.

        5. **Error handling**: Any exception during execution is caught and
           returned as a FAIL result with the error message and traceback.

        The hypothesis code must define a ``run(benchmark_data: dict) -> dict``
        function that returns metrics.

    Args:
        hypothesis_code: Python source code as a string. Must define a
            ``run(benchmark_data)`` function.
        benchmark_data: Dict passed to the hypothesis's ``run()`` function.
            Typically contains training data, model configs, etc.
        config: Sandbox configuration. If None, uses defaults.

    Returns:
        SandboxResult with success/failure, metrics, captured I/O, and timing.

    For example::

        code = '''
        def run(data):
            return {"final_energy": 0.5, "wall_clock_seconds": 1.2}
        '''
        result = run_in_sandbox(code, {"dataset": [1, 2, 3]})
        assert result.success
        assert result.metrics["final_energy"] == 0.5

    Spec: REQ-AUTO-004, REQ-AUTO-009
    """
    if config is None:
        config = SandboxConfig()

    # --- Step 1: Static analysis — check for blocked imports ---
    violations = check_imports(hypothesis_code, config.blocked_modules)
    if violations:
        return SandboxResult(
            success=False,
            error=f"Blocked imports detected: {', '.join(violations)}",
        )

    # --- Step 2: Execute in isolated namespace with timeout ---
    stdout_capture = io.StringIO()
    stderr_capture = io.StringIO()
    start_time = time.monotonic()

    # Flag to track if we hit the timeout
    timed_out = False

    def timeout_handler(signum: int, frame: Any) -> None:
        """Signal handler for SIGALRM — raises TimeoutError to abort execution."""
        nonlocal timed_out
        timed_out = True
        raise TimeoutError("Hypothesis execution timed out")

    # Create an isolated namespace with only builtins (no access to our globals)
    namespace: dict[str, Any] = {"__builtins__": __builtins__}

    try:
        # Set up SIGALRM timeout (Unix only — will not work on Windows)
        old_handler = signal.signal(signal.SIGALRM, timeout_handler)
        signal.alarm(config.timeout_seconds)

        try:
            # Compile and execute the hypothesis code in the isolated namespace.
            # redirect_stdout/stderr capture all print output.
            with redirect_stdout(stdout_capture), redirect_stderr(stderr_capture):
                exec(compile(hypothesis_code, "<hypothesis>", "exec"), namespace)

                # The hypothesis must define a run() function
                if "run" not in namespace:
                    return SandboxResult(
                        success=False,
                        error="Hypothesis must define a `run(benchmark_data)` function",
                        stdout=stdout_capture.getvalue(),
                        stderr=stderr_capture.getvalue(),
                        wall_clock_seconds=time.monotonic() - start_time,
                    )

                # Call the hypothesis's run function with the benchmark data
                metrics = namespace["run"](benchmark_data)

                # Validate that run() returned a dict (not None, int, etc.)
                if not isinstance(metrics, dict):
                    return SandboxResult(
                        success=False,
                        error=f"run() must return a dict, got {type(metrics).__name__}",
                        stdout=stdout_capture.getvalue(),
                        stderr=stderr_capture.getvalue(),
                        wall_clock_seconds=time.monotonic() - start_time,
                    )

        finally:
            # Always cancel the alarm and restore the old signal handler,
            # even if an exception occurred
            signal.alarm(0)
            signal.signal(signal.SIGALRM, old_handler)

    except TimeoutError:
        return SandboxResult(
            success=False,
            error="Hypothesis execution timed out",
            stdout=stdout_capture.getvalue(),
            stderr=stderr_capture.getvalue(),
            wall_clock_seconds=time.monotonic() - start_time,
            timed_out=True,
        )
    except Exception as e:
        # Catch any other exception (RuntimeError, ValueError, JAX errors, etc.)
        return SandboxResult(
            success=False,
            error=f"{type(e).__name__}: {e}",
            stdout=stdout_capture.getvalue(),
            stderr=stderr_capture.getvalue() + "\n" + traceback.format_exc(),
            wall_clock_seconds=time.monotonic() - start_time,
        )

    elapsed = time.monotonic() - start_time
    return SandboxResult(
        success=True,
        metrics=metrics,
        stdout=stdout_capture.getvalue(),
        stderr=stderr_capture.getvalue(),
        wall_clock_seconds=elapsed,
    )
