"""Cross-language validation: JAX → Rust transpilation support.

**Researcher summary:**
    Generates test vectors from JAX hypothesis runs, validates that Rust
    implementations produce matching energy values (within fp tolerance),
    and verifies Rust meets or exceeds JAX wall-clock performance.

**Detailed explanation for engineers:**
    When the autoresearch loop accepts a hypothesis (a new sampler config,
    training tweak, etc.), that hypothesis was evaluated in Python/JAX.
    Before it can be deployed as production Rust code, we need to verify
    that the Rust implementation produces the same results.

    This module provides the validation infrastructure:

    1. **Test vector generation**: Run the JAX hypothesis on a set of
       reference inputs and record the exact outputs (energy values,
       gradients). These become the "ground truth" that Rust must match.

    2. **Conformance checking**: Given Rust outputs for the same inputs,
       verify they match JAX outputs within floating-point tolerance.
       This catches bugs in manual or agent-assisted JAX→Rust translation.

    3. **Performance gate**: Verify the Rust implementation is at least
       as fast as JAX. If Rust is slower, the transpilation has a problem.

    **The actual translation (JAX code → Rust code) is done by an LLM agent
    or a human.** This module doesn't generate Rust code — it validates that
    whatever Rust code was produced is correct and fast enough.

    The workflow is:
    ```
    JAX hypothesis passes evaluation
      → generate_test_vectors() captures reference inputs/outputs
      → Human or LLM agent writes Rust implementation
      → validate_conformance() checks Rust matches JAX
      → validate_performance() checks Rust is fast enough
      → If both pass: merge to production
    ```

Spec: REQ-AUTO-006
"""

from __future__ import annotations

import json
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable

import jax
import jax.numpy as jnp
import jax.random as jrandom


@dataclass
class TestVector:
    """A single input-output pair for cross-language validation.

    **For engineers:**
        A test vector records: "for this specific input, JAX computed this
        exact energy value." The Rust implementation must produce the same
        value (within tolerance) for the same input.

    Spec: REQ-AUTO-006
    """

    input: list[float]
    expected_energy: float
    expected_gradient: list[float] | None = None


@dataclass
class TestVectorSet:
    """A collection of test vectors for validating one hypothesis.

    **For engineers:**
        Generated by ``generate_test_vectors()``, saved as JSON, and
        loaded by the Rust conformance test harness.

    Spec: REQ-AUTO-006
    """

    hypothesis_id: str
    vectors: list[TestVector] = field(default_factory=list)
    jax_wall_clock_seconds: float = 0.0

    def save(self, path: Path) -> None:
        """Save test vectors to JSON for the Rust conformance harness."""
        data = {
            "hypothesis_id": self.hypothesis_id,
            "jax_wall_clock_seconds": self.jax_wall_clock_seconds,
            "vectors": [
                {
                    "input": v.input,
                    "expected_energy": v.expected_energy,
                    "expected_gradient": v.expected_gradient,
                }
                for v in self.vectors
            ],
        }
        path.write_text(json.dumps(data, indent=2))

    @classmethod
    def load(cls, path: Path) -> TestVectorSet:
        """Load test vectors from JSON."""
        data = json.loads(path.read_text())
        vectors = [
            TestVector(
                input=v["input"],
                expected_energy=v["expected_energy"],
                expected_gradient=v.get("expected_gradient"),
            )
            for v in data["vectors"]
        ]
        return cls(
            hypothesis_id=data["hypothesis_id"],
            vectors=vectors,
            jax_wall_clock_seconds=data.get("jax_wall_clock_seconds", 0.0),
        )


def generate_test_vectors(
    hypothesis_id: str,
    energy_fn: Any,
    input_dim: int,
    n_vectors: int = 20,
    include_gradients: bool = True,
    key: jax.Array | None = None,
) -> TestVectorSet:
    """Generate test vectors by running JAX energy function on reference inputs.

    **Researcher summary:**
        Evaluates energy_fn on n_vectors random inputs, recording exact
        energy values and optionally gradients. Also times the computation
        for the performance gate.

    **Detailed explanation for engineers:**
        This function creates the "answer key" that the Rust implementation
        must match. It generates random inputs, evaluates the JAX energy
        function on each, and records the results.

        The inputs are drawn from a standard normal distribution. This
        provides a good spread of test points across the input space.

    Args:
        hypothesis_id: Identifier for this hypothesis (for tracking).
        energy_fn: JAX energy function with an ``energy(x)`` method and
            optionally a ``grad_energy(x)`` method.
        input_dim: Dimensionality of the input space.
        n_vectors: Number of test vectors to generate. More = more thorough
            but slower Rust conformance testing. 20 is a good default.
        include_gradients: If True, also record gradient values.
        key: JAX PRNG key. Uses default if None.

    Returns:
        TestVectorSet with the reference input-output pairs.

    For example::

        from carnot.models.ising import IsingModel, IsingConfig
        model = IsingModel(IsingConfig(input_dim=10))
        vectors = generate_test_vectors("hyp-001", model, input_dim=10)
        vectors.save(Path("test_vectors.json"))

    Spec: REQ-AUTO-006
    """
    if key is None:
        key = jrandom.PRNGKey(0)

    vectors: list[TestVector] = []

    # Time the JAX computation for the performance gate
    start = time.monotonic()

    for i in range(n_vectors):
        key, subkey = jrandom.split(key)
        x = jrandom.normal(subkey, (input_dim,))

        energy_val = float(energy_fn.energy(x))

        grad_val = None
        if include_gradients and hasattr(energy_fn, "grad_energy"):
            grad = energy_fn.grad_energy(x)
            grad_val = [float(g) for g in grad]

        vectors.append(TestVector(
            input=[float(v) for v in x],
            expected_energy=energy_val,
            expected_gradient=grad_val,
        ))

    elapsed = time.monotonic() - start

    return TestVectorSet(
        hypothesis_id=hypothesis_id,
        vectors=vectors,
        jax_wall_clock_seconds=elapsed,
    )


@dataclass
class ConformanceResult:
    """Result of cross-language conformance validation.

    **For engineers:**
        Reports whether the Rust implementation matches JAX outputs,
        with per-vector details and overall pass/fail.

    Spec: REQ-AUTO-006
    """

    passed: bool
    total_vectors: int
    matching_vectors: int
    max_energy_error: float
    max_gradient_error: float | None
    failures: list[str] = field(default_factory=list)


def validate_conformance(
    test_vectors: TestVectorSet,
    rust_energies: list[float],
    rust_gradients: list[list[float]] | None = None,
    energy_tolerance: float = 1e-4,
    gradient_tolerance: float = 1e-3,
) -> ConformanceResult:
    """Validate that Rust outputs match JAX reference outputs.

    **Researcher summary:**
        Compares Rust energy/gradient values against JAX test vectors
        within configurable tolerance. Reports max error and failure details.

    **Detailed explanation for engineers:**
        For each test vector, checks:
        1. |rust_energy - jax_energy| < energy_tolerance
        2. max(|rust_gradient - jax_gradient|) < gradient_tolerance (if gradients provided)

        If any vector fails either check, the result is FAIL with details.

    Args:
        test_vectors: Reference JAX outputs from generate_test_vectors().
        rust_energies: Energy values computed by the Rust implementation
            for the same inputs. Must have same length as test_vectors.vectors.
        rust_gradients: Optional gradient values from Rust. If provided,
            must have same length and dimensionality as test_vectors.
        energy_tolerance: Maximum allowed |rust - jax| energy difference.
        gradient_tolerance: Maximum allowed |rust - jax| gradient difference.

    Returns:
        ConformanceResult with pass/fail, error magnitudes, and failure details.

    Spec: REQ-AUTO-006
    """
    vectors = test_vectors.vectors
    assert len(rust_energies) == len(vectors), (
        f"Expected {len(vectors)} energies, got {len(rust_energies)}"
    )

    matching = 0
    max_energy_err = 0.0
    max_grad_err: float | None = None if rust_gradients is None else 0.0
    failures: list[str] = []

    for i, (vec, rust_e) in enumerate(zip(vectors, rust_energies)):
        energy_err = abs(rust_e - vec.expected_energy)
        max_energy_err = max(max_energy_err, energy_err)

        if energy_err > energy_tolerance:
            failures.append(
                f"Vector {i}: energy mismatch rust={rust_e}, jax={vec.expected_energy}, "
                f"err={energy_err}"
            )
            continue

        # Check gradient if provided
        if rust_gradients is not None and vec.expected_gradient is not None:
            rust_g = rust_gradients[i]
            grad_err = max(
                abs(r - j) for r, j in zip(rust_g, vec.expected_gradient)
            )
            assert max_grad_err is not None
            max_grad_err = max(max_grad_err, grad_err)
            if grad_err > gradient_tolerance:
                failures.append(
                    f"Vector {i}: gradient mismatch max_err={grad_err}"
                )
                continue

        matching += 1

    return ConformanceResult(
        passed=len(failures) == 0,
        total_vectors=len(vectors),
        matching_vectors=matching,
        max_energy_error=max_energy_err,
        max_gradient_error=max_grad_err,
        failures=failures,
    )


def validate_performance(
    jax_seconds: float,
    rust_seconds: float,
    max_ratio: float = 1.0,
) -> bool:
    """Validate that Rust is at least as fast as JAX.

    **For engineers:**
        The Rust implementation should be faster (or at worst equal) to JAX.
        Returns True if rust_seconds <= jax_seconds * max_ratio.

    Args:
        jax_seconds: Wall-clock time for JAX computation.
        rust_seconds: Wall-clock time for Rust computation.
        max_ratio: Maximum allowed rust/jax time ratio. Default 1.0
            (Rust must be at least as fast). Set > 1.0 to allow some slack.

    Spec: REQ-AUTO-006
    """
    if jax_seconds <= 0:
        return True  # can't compare if JAX time is zero
    return rust_seconds <= jax_seconds * max_ratio
