with open("research-references.md", "a") as f:
    f.write("\n## 2026-05-11 Post-.139 Planning Sweep (Milestone 2026.05.140)\n\n")
    f.write("This sweep was run after milestone `.139` completed. The literature search revealed advances in latent space reasoning, constrained physical models, and enhanced hardware dynamics.\n\n")
    f.write("### Energy-Based Calibration for Implicit CoT (EBM-CoT)\n")
    f.write("- **Paper:** \"Think Consistently, Reason Efficiently: Energy-Based Calibration for Implicit CoT\" (arXiv:2511.07124)\n")
    f.write("- **What:** Uses EBMs to calibrate latent \"thought\" embeddings in LLMs via Langevin updates, ensuring global logical consistency before text decoding.\n")
    f.write("- **Relevance to Carnot:** Extends our continuous latent reasoning (Phase-7) by providing a concrete mechanism to correct hidden states on-the-fly.\n\n")
    f.write("### Constraint Informed KANs (CIKAN)\n")
    f.write("- **Paper:** \"CIKAN: Constraint Informed Kolmogorov-Arnold Networks...\" (PMLR 2025)\n")
    f.write("- **What:** Integrates hard constraints directly into the KAN architecture to approximate complex control governors.\n")
    f.write("- **Relevance to Carnot:** Provides the theoretical basis for Tier-4 Adaptive Energy Landscapes, allowing KANs to natively respect bounds without external penalty loops.\n\n")
    f.write("### Bounce-Bind Ising Machine (BBIM) for FPGA\n")
    f.write("- **Paper:** \"Bounce-Bind Ising Machine...\" (2026)\n")
    f.write("- **What:** Introduces a tunable parameter to modulate Gibbs sampling/Glauber dynamics on FPGAs to escape local minima faster.\n")
    f.write("- **Relevance to Carnot:** A crucial RTL enhancement for the KV260 hardware track to accelerate convergence in dense constraint graphs.\n")
