"""LIVE ARC-AGI-3 multi-game run: replay our OFFLINE-reproduced game solutions against
the LIVE scored env under ONE scorecard. Mode-1 pure action replay (no re-solving, no
verifier needed at submit-time).

The replay set is sourced DYNAMICALLY from the latest validated submission package
(`results/experiment_*submission_package*.json`, the conductor-prepared + env-match-validated
manifest), intersected with the games the metaharness banked-trajectory loader can actually
replay. This keeps the live-submit driver from going stale as `reproducible_total_levels`
grows: when the conductor reproduces a new game / deeper level and refreshes the package, the
driver picks it up automatically. The prior hardcoded 11-game/13-level set (the 2026-06-17
FIRST submission) is preserved as CLAIMED_FALLBACK and used only if no package is found.

  As of the 2026-06-21 outer-loop refresh: the latest package (exp4473, 22 env-matched games /
  45 levels) yields 16 metaharness-loadable games / 39 claimed levels — a large jump over the
  13 levels actually submitted on 2026-06-17. The 6 package games with no replayable banked
  action sequence (graph-explore solves: dc22/ft09/g50t/s5i5/sb26/vc33) are skipped here; they
  need a banked action trajectory before they can be live-replayed.

TWO-PHASE (per the operator's choice 2026-06-17 "validate all live, then submit"):
  DEFAULT (no --submit): VALIDATE — open a scorecard, play every game live, read the level
    each reaches, and DO NOT close it (an unclosed scorecard is NOT submitted; no leaderboard
    record). Reports which games env-match live. ALWAYS run this first: a game that reproduces
    OFFLINE is not guaranteed to env-match LIVE; validate surfaces mismatches before any submit.
  --submit: SUBMIT — same play-through, then CLOSE the scorecard (records the score on the
    leaderboard). Operator-gated, irreversible. External Publication is operator-only.

Usage:
  .venv/bin/python scripts/arc3_live_submit.py            # VALIDATE live (no submission)
  .venv/bin/python scripts/arc3_live_submit.py --submit   # SUBMIT (close scorecard) — operator-gated
"""
from __future__ import annotations

import importlib.util
import json
import subprocess
import sys
import time
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "python"))

from arcengine import GameAction

# the 11 reproduced games + their claimed level as of the FIRST live submission (2026-06-17,
# 13 levels). Preserved as the fallback used only when no validated package is found.
CLAIMED_FALLBACK = {"r11l": 1, "lp85": 3, "ls20": 1, "wa30": 1, "cd82": 1, "sp80": 1,
                    "su15": 1, "tu93": 1, "cn04": 1, "m0r0": 1, "sk48": 1}


def _latest_package() -> dict | None:
    """Return the package_manifest of the newest conductor-prepared submission package, or None.

    Globs the submission-package-prep artifacts and picks the most recently modified one so the
    driver auto-tracks conductor refreshes (exp4460 -> exp4473 -> ...) without a code edit."""
    cands = sorted(
        (REPO / "results").glob("experiment_*submission_package*.json"),
        key=lambda p: p.stat().st_mtime, reverse=True)
    for p in cands:
        try:
            d = json.loads(p.read_text())
        except Exception:
            continue
        manifest = d.get("package_manifest")
        if isinstance(manifest, list) and manifest:
            return {"path": p.name, "manifest": manifest}
    return None


def _offline_reached() -> dict:
    """{game: levels_completed} from the OFFLINE aggregate scorecard, or {} if absent.

    This is the source of truth for what each game's banked FLAT trajectory actually replays to
    (regenerated by `python scripts/arc3_replay_scorecard_metaharness.py`, OFFLINE/zero-quota).
    The package manifest's `levels` is the reproduce-GATE depth (per-level plan dicts); the live
    driver replays the FLAT concatenated trajectory, which can be shallower when deeper levels are
    reproduced but not yet flat-banked. Capping the claim to this number keeps the driver honest."""
    p = REPO / "results" / "arc3_replay_aggregate_scorecard.json"
    if not p.exists():
        return {}
    try:
        d = json.loads(p.read_text())
    except Exception:
        return {}
    return {g.get("game"): int(g.get("levels_completed", 0) or 0)
            for g in (d.get("per_game") or []) if g.get("game")}


def _build_claimed(mh) -> tuple[dict, dict]:
    """Build {game: claimed_levels} from the latest validated package, intersected with the games
    the metaharness can actually replay (non-empty banked action sequence) and CAPPED to the level
    the flat trajectory reaches offline (so the driver never over-claims). Falls back to the
    2026-06-17 hardcoded set if no package or no loadable game is found.

    Returns (claimed_dict, info) where info records provenance: source, the per-game caps applied
    (deeper levels reproduced-but-not-flat-banked), and the uncapped-vs-capped totals."""
    pkg = _latest_package()
    if pkg is None:
        return dict(CLAIMED_FALLBACK), {"source": "hardcoded_fallback_2026_06_17", "capped": []}
    reached = _offline_reached()
    claimed: dict[str, int] = {}
    capped: list[dict] = []
    trajectory_sources: dict[str, str] = {}
    adaptive_solvers: dict[str, str] = {}
    uncapped_total = 0
    for row in pkg["manifest"]:
        game = row.get("game")
        if not game or not row.get("env_matched"):
            continue
        src = row.get("trajectory_path") or row.get("source") or mh.RESOLVED_ARTIFACTS.get(game, mh.GAME_ARTIFACTS.get(game))
        actions = []
        if src:
            try:
                actions = mh.load_actions(src)
            except Exception:
                actions = []
        if not actions:
            continue  # no replayable banked trajectory (e.g. graph-explore solve) -> skip
        pkg_levels = int(row.get("levels", 1) or 1)
        uncapped_total += pkg_levels
        # cap to the flat-replay-reachable level when we know it (game present in the offline
        # aggregate), or to package-provided fresh offline replay depth for refreshed packages.
        # An unknown game keeps its package claim and the live VALIDATE step catches it.
        offline = row.get("offline_reproduced_level")
        offline = int(offline) if offline is not None else reached.get(game)
        lvl = min(pkg_levels, offline) if offline is not None else pkg_levels
        if offline is not None and offline < pkg_levels:
            capped.append({"game": game, "package_levels": pkg_levels, "offline_reached": offline})
        claimed[game] = lvl
        trajectory_sources[game] = str(src)
        if row.get("adaptive_solver"):
            adaptive_solvers[game] = str(row.get("adaptive_solver"))
    if not claimed:
        return dict(CLAIMED_FALLBACK), {"source": "hardcoded_fallback_2026_06_17", "capped": []}
    info = {"source": f"package:{pkg['path']}", "capped": capped,
            "uncapped_package_total": uncapped_total, "capped_total": sum(claimed.values()),
            "trajectory_sources": trajectory_sources, "adaptive_solvers": adaptive_solvers}
    return claimed, info


def _load_metaharness():
    spec = importlib.util.spec_from_file_location(
        "mh", str(REPO / "scripts" / "arc3_replay_scorecard_metaharness.py"))
    mh = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mh)  # type: ignore
    return mh


def _arc_api_key() -> str:
    out = subprocess.run(["sops", "-d", str(REPO / "secrets" / "arc_api.enc.yaml")],
                         capture_output=True, text=True, check=True).stdout
    import yaml
    return str(yaml.safe_load(out)["ARC_API_KEY"])


def online_arcade():
    from arc_agi import Arcade
    from arc_agi.base import OperationMode
    return Arcade(arc_api_key=_arc_api_key(), operation_mode=OperationMode.ONLINE,
                  environments_dir="", recordings_dir=str(REPO / "recordings" / "arc_live_submit"))


def resolve_game_id(arcade, short: str) -> str:
    for info in arcade.get_environments():
        gid = getattr(info, "game_id", getattr(info, "id", "")) or ""
        if str(gid).split("-", 1)[0] == short:
            return str(gid)
    return short


def replay_live(arcade, short: str, scorecard_id: str, actions: list[dict], mh, corpus=None) -> tuple[int, str]:
    gid = resolve_game_id(arcade, short)
    env = arcade.make(gid, scorecard_id=scorecard_id)
    frame = env.reset()
    from carnot.agentic.arc_agi3_live_adapter import _levels_completed
    from carnot.agentic.arc_agi3_world_model import grid_of
    # capture the per-game session guid -> the browser replay URL is
    # https://arcprize.org/replay/<guid> (verified 2026-06-30). Recorded so the
    # artifact carries a directly-viewable link per game.
    guid = str(getattr(frame, "guid", "") or "") if frame is not None else ""
    prev_grid = grid_of(frame) if frame is not None else None
    prev_lvl = _levels_completed(frame) if frame is not None else 0
    for a in actions:
        aid, data = mh.normalize(a)
        if aid is None:
            continue
        ge = getattr(GameAction, f"ACTION{aid}")
        frame = env.step(ge, data=data, reasoning={"policy": "offline_reproduced_replay"})
        if frame is None:
            break
        # CAPTURE the live transition for learning/debugging (non-fatal -- never break a submission).
        # Feeds the transition corpus (the exact live behaviour, incl. env-mismatch cases like sc25).
        if corpus is not None and prev_grid is not None:
            try:
                ng = grid_of(frame)
                lvl = _levels_completed(frame)
                corpus.add(short, prev_grid, aid, data, ng, prev_lvl, lvl)
                prev_grid, prev_lvl = ng, lvl
            except Exception:
                pass
    return (_levels_completed(frame) if frame is not None else -1), guid


def main(argv) -> int:
    submit = "--submit" in argv
    mh = _load_metaharness()
    claimed_set, claimed_info = _build_claimed(mh)
    claimed_source = claimed_info["source"]
    mode = "SUBMIT (will CLOSE scorecard — leaderboard record)" if submit else "VALIDATE (no close, no submission)"
    print(f"== LIVE ARC-AGI-3 multi-game replay — mode: {mode} ==", flush=True)
    print(f"  replay set source: {claimed_source}", flush=True)
    print(f"  games: {len(claimed_set)}  claimed levels: {sum(claimed_set.values())} "
          f"(flat-replay-capped; package nominal {claimed_info.get('uncapped_package_total', '?')})", flush=True)
    for c in claimed_info.get("capped", []):
        print(f"    note: {c['game']} reproduced to L{c['package_levels']} but flat-banked only to "
              f"L{c['offline_reached']} — claiming L{c['offline_reached']} (deeper levels not yet flat-banked)",
              flush=True)

    arcade = online_arcade()
    scorecard_id = arcade.open_scorecard()
    print(f"  opened LIVE scorecard: {scorecard_id}", flush=True)

    # CAPTURE live transitions into the corpus (recording ON, 2026-06-21) -- non-fatal; the SDK also
    # records frames to recordings_dir. This is the live-play half of the transition-capture sink.
    try:
        from carnot.agentic.arc_transition_capture import TransitionCorpus
        corpus = TransitionCorpus()
    except Exception:
        corpus = None

    rows, total, matched = [], 0, 0
    for short, claimed in claimed_set.items():
        src = claimed_info.get("trajectory_sources", {}).get(short) or mh.RESOLVED_ARTIFACTS.get(short, mh.GAME_ARTIFACTS.get(short))
        actions = mh.load_actions(src) if src else []
        if not actions:
            rows.append({"game": short, "claimed": claimed, "live_level": None, "error": "no banked actions"})
            print(f"    {short:5} claimed L{claimed} -> NO banked actions (skip)", flush=True)
            continue
        t0 = time.time()
        try:
            lvl, guid = replay_live(arcade, short, scorecard_id, actions, mh, corpus=corpus)
        except Exception as e:
            rows.append({"game": short, "claimed": claimed, "live_level": None, "error": repr(e)[:140]})
            print(f"    {short:5} claimed L{claimed} -> ERROR {repr(e)[:70]}", flush=True)
            continue
        ok = lvl >= claimed
        matched += int(ok)
        total += max(0, lvl)
        rows.append({"game": short, "claimed": claimed, "live_level": lvl, "env_match": ok,
                     "guid": guid, "replay_url": f"https://arcprize.org/replay/{guid}" if guid else None})
        print(f"    {short:5} claimed L{claimed} -> LIVE L{lvl}  {'MATCH' if ok else 'MISMATCH'}  "
              f"[{time.time()-t0:.0f}s]  {('https://arcprize.org/replay/' + guid) if guid else ''}", flush=True)

    if corpus is not None:
        try:
            captured = corpus.flush()
            print(f"  captured live transitions -> corpus: {sum(captured.values()) if captured else 0} new",
                  flush=True)
        except Exception:
            pass

    print(f"\n  LIVE TOTAL: {total} levels; {matched}/{len(claimed_set)} games env-matched", flush=True)

    submitted = False
    if submit:
        card = arcade.close_scorecard(scorecard_id)
        submitted = card is not None
        print(f"  SUBMITTED: scorecard CLOSED -> leaderboard record ({type(card).__name__ if card else 'None'})", flush=True)
    else:
        print("  NOT submitted (scorecard left open; no leaderboard record). Re-run with --submit to record.", flush=True)

    out = REPO / "results" / "arc3_live_submit.json"
    out.write_text(json.dumps({
        "experiment": "arc3_live_submit", "mode": "submit" if submit else "validate",
        "scorecard_id": scorecard_id, "replay_base": "https://arcprize.org/replay/",
        "live_total_levels": total,
        "games_env_matched": matched, "games": len(claimed_set),
        "claimed_total_levels": sum(claimed_set.values()), "per_game": rows,
        "replay_set_source": claimed_source, "claimed_caps": claimed_info.get("capped", []),
        "uncapped_package_total": claimed_info.get("uncapped_package_total"),
        "leaderboard_submitted": submitted,
        "run_date": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "trajectory_sources": claimed_info.get("trajectory_sources", {}),
        "adaptive_solvers": claimed_info.get("adaptive_solvers", {}),
        "inference_substrate": "live_arc_agi3_env_multi_game_replay",
    }, indent=2))
    print(f"  wrote {out.relative_to(REPO)}", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
