#!/usr/bin/env bash
# Sweep all Carnot-EBM HF model cards for Paper-v6 Narrowing Discipline
# forbidden phrasings. Output: findings report; no auto-edits.
set -uo pipefail
HF=/home/ianblenke/github.com/ianblenke/carnot/.venv/bin/hf
WORKDIR=$(mktemp -d)
REPORT=ops/hf_paper_v6_narrowing_audit.md
trap "rm -rf $WORKDIR" EXIT

# Get current repo list from the HF API (fresh after Tier A/B/C edits).
mapfile -t REPOS < <(curl -s "https://huggingface.co/api/models?author=Carnot-EBM&limit=200" \
  | python3 -c "import json,sys;[print(m['id']) for m in sorted(json.load(sys.stdin),key=lambda x:x['id'])]")

cat > "$REPORT" <<'EOF'
# HF Model Card Paper-v6 Narrowing Audit

Generated by `scripts/hf_paper_v6_narrowing_audit.sh` post-Tier-A/B/C/D cleanup.

Sweep targets the eleven retracted claims from CLAUDE.md "Paper-v6
Narrowing Discipline" (2026-05-23 Deep Think). A hit does not necessarily
mean a violation — context matters. This is a triage report; operator
decides what to act on.

## Forbidden phrasings scanned

| Pattern | Origin |
|---|---|
| `thermaliz` / `equilibrium` / `Boltzmann-distributed` | #2 KV260 thermalization claim |
| `KV260.*speedup` / `FPGA.*speedup` / `\dx\s*speedup` | #3 KV260 hardware speedup |
| `0\.9857` / `\+0\.0621` | #11 FoVer headline AUROC v2 |
| `hardware sovereignty` / `local edge deployability` | #9 framing flip |
| `5 paper_ready` / `five-streak` | #10 maturity-via-streak |
| `Extropic Z1` (as production target without "future work" gloss) | #7 |
| `verifier ensemble.*generalizes` / `universally` | #8 |

## Findings

EOF

for repo in "${REPOS[@]}"; do
  card="$WORKDIR/$(echo "$repo" | tr / _).md"
  curl -sf "https://huggingface.co/$repo/raw/main/README.md" -o "$card" 2>/dev/null || continue

  hits=$(python3 -c "
import re, sys
content = open('$card').read()
patterns = {
    'thermalization (KV260 #2)': r'\bthermaliz|equilibrium samples|Boltzmann-distributed',
    'KV260/FPGA speedup (#3)': r'KV260.{0,40}(speedup|faster than CPU|hardware acceleration)|FPGA.{0,40}speedup|\b1[0-9]+x\s*(speedup|faster)',
    'FoVer v2 headline 0.9857 (#11)': r'\b0\.9857\b|\+0\.0621',
    'hardware sovereignty (#9)': r'hardware sovereignty',
    'five-paper-ready streak (#10)': r'five.{0,20}paper.?ready|paper.?ready.{0,30}streak|\b5\s*/\s*5\s*paper.?ready',
    'Extropic Z1 as production target (#7)': r'Extropic.{0,30}(production|target|deploy)(?!.{0,80}future)',
    'verifier ensemble universal generalization (#8)': r'verifier ensemble.{0,40}(generalize|universal|all corpora|any modality)',
}
for label, pat in patterns.items():
    for m in re.finditer(pat, content, re.IGNORECASE):
        start, end = m.span()
        ctx = content[max(0,start-50):min(len(content),end+50)].replace(chr(10),' ')
        print(f'  - **{label}**: \`...{ctx}...\`')
" 2>/dev/null)

  if [ -n "$hits" ]; then
    echo "" >> "$REPORT"
    echo "### \`$repo\`" >> "$REPORT"
    echo "" >> "$REPORT"
    echo "$hits" >> "$REPORT"
  fi
done

# Summary footer
cat >> "$REPORT" <<EOF

## Run metadata

- Sweep date: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
- Repos scanned: ${#REPOS[@]}
- Source: \`scripts/hf_paper_v6_narrowing_audit.sh\` (transient; promote to \`scripts/\` if recurring)
EOF

echo "report -> $REPORT"
wc -l "$REPORT"
