# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/carnot_ising_bd/carnot_ising_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==carnot_ising_bd || ORIG_REF_NAME==carnot_ising_bd} -quiet] -quiet

# IP: bd/carnot_ising_bd/ip/carnot_ising_bd_zynq_ultra_ps_e_0_0/carnot_ising_bd_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==carnot_ising_bd_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==carnot_ising_bd_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/carnot_ising_bd/ip/carnot_ising_bd_axi_smartconnect_0_0/carnot_ising_bd_axi_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==carnot_ising_bd_axi_smartconnect_0_0 || ORIG_REF_NAME==carnot_ising_bd_axi_smartconnect_0_0} -quiet] -quiet

# IP: bd/carnot_ising_bd/ip/carnot_ising_bd_proc_sys_reset_0_0/carnot_ising_bd_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==carnot_ising_bd_proc_sys_reset_0_0 || ORIG_REF_NAME==carnot_ising_bd_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/carnot_ising_bd/ip/carnot_ising_bd_ising_sampler_0_0/carnot_ising_bd_ising_sampler_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==carnot_ising_bd_ising_sampler_0_0 || ORIG_REF_NAME==carnot_ising_bd_ising_sampler_0_0} -quiet] -quiet

# XDC: /home/ianblenke/github.com/ianblenke/carnot/output/carnot_ising_bd/project/carnot_ising.gen/sources_1/bd/carnot_ising_bd/carnot_ising_bd_ooc.xdc
