# Vivado non-project synthesis for ising_sampler_v3 — auto-generated by Exp 701.
# Target: xck26-sfvc784-2LV-c
# Spec: REQ-HW-037, REQ-HW-038
read_verilog /home/ianblenke/github.com/ianblenke/carnot/rtl/ising_sampler_v3.v
synth_design -top ising_sampler_v3 -part xck26-sfvc784-2LV-c
report_utilization -file /home/ianblenke/github.com/ianblenke/carnot/results/ising_v3_utilization.rpt
report_timing_summary -file /home/ianblenke/github.com/ianblenke/carnot/results/ising_v3_timing.rpt
