# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ianblenke/github.com/ianblenke/carnot/output/carnot_ising_bd/project/carnot_ising.srcs/sources_1/bd/carnot_ising_bd/ip/carnot_ising_bd_ising_sampler_0_0/carnot_ising_bd_ising_sampler_0_0.xci
# IP: The module: 'carnot_ising_bd_ising_sampler_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ianblenke/github.com/ianblenke/carnot/output/carnot_ising_bd/project/carnot_ising.gen/sources_1/bd/carnot_ising_bd/ip/carnot_ising_bd_ising_sampler_0_0/carnot_ising_bd_ising_sampler_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'carnot_ising_bd_ising_sampler_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/ianblenke/github.com/ianblenke/carnot/output/carnot_ising_bd/project/carnot_ising.gen/sources_1/bd/carnot_ising_bd/ip/carnot_ising_bd_ising_sampler_0_0/carnot_ising_bd_ising_sampler_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'carnot_ising_bd_ising_sampler_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/ianblenke/github.com/ianblenke/carnot/output/carnot_ising_bd/project/carnot_ising.srcs/sources_1/bd/carnot_ising_bd/ip/carnot_ising_bd_ising_sampler_0_0/carnot_ising_bd_ising_sampler_0_0.xci
# IP: The module: 'carnot_ising_bd_ising_sampler_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ianblenke/github.com/ianblenke/carnot/output/carnot_ising_bd/project/carnot_ising.gen/sources_1/bd/carnot_ising_bd/ip/carnot_ising_bd_ising_sampler_0_0/carnot_ising_bd_ising_sampler_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'carnot_ising_bd_ising_sampler_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/ianblenke/github.com/ianblenke/carnot/output/carnot_ising_bd/project/carnot_ising.gen/sources_1/bd/carnot_ising_bd/ip/carnot_ising_bd_ising_sampler_0_0/carnot_ising_bd_ising_sampler_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'carnot_ising_bd_ising_sampler_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
