"""Constraint extraction pipeline for automated verification.

Extracts verifiable constraints from text, code, and natural language,
then maps them to energy terms for Ising-model verification.

Spec: REQ-VERIFY-001, REQ-VERIFY-002, REQ-VERIFY-003
"""

from carnot.pipeline.agentic import (
    AgentStep,
    ConstraintState,
    FactStatus,
    TrackedFact,
    propagate,
)
from carnot.pipeline.case_memory import (
    CaseEntry,
    CaseKey,
    CaseMatch,
    CaseMemory,
    CaseProvenance,
    CaseQuery,
    CaseRecord,
)
from carnot.pipeline.code_learning import (
    CodeVerificationTrace,
    LearningCurvePoint,
    LearningImprovement,
    ProblemTypeScore,
    PropertyFailureTrace,
    PropertyRanker,
    PropertyScore,
    RepairStrategy,
    StrategyRecommendation,
    TraceAnalysis,
    TraceAnalyzer,
    VerificationTraceStep,
)
from carnot.pipeline.code_verification import verify_code
from carnot.pipeline.errors import (
    CarnotError,
    ExtractionError,
    ModelLoadError,
    PipelineTimeoutError,
    RepairError,
    VerificationError,
)
from carnot.pipeline.extract import (
    ArithmeticExtractor,
    AutoExtractor,
    CodeExtractor,
    ConstraintExtractor,
    ConstraintResult,
    LogicExtractor,
    NLExtractor,
)
from carnot.pipeline.llm_extractor import LLMConstraintExtractor
from carnot.pipeline.memory import PATTERN_THRESHOLD, ConstraintMemory
from carnot.pipeline.mining import (
    FailureAnalyzer,
    FailureReport,
    FalseNegative,
)
from carnot.pipeline.pbt_code_verifier import (
    PBTCodeVerificationResult,
    PBTCodeVerifier,
    PBTDerivedProperty,
    PBTPropertyFailure,
)
from carnot.pipeline.property_code_verifier import (
    DerivedProperty,
    PropertyCodeVerificationResult,
    PropertyCodeVerifier,
    PropertyFailure,
    extract_official_test_examples,
    extract_prompt_examples,
)
from carnot.pipeline.self_learning_policy import (
    PolicyProvenance,
    PolicyQuery,
    PropertyBudgetUpdate,
    RepairPromptPatch,
    RoutingHint,
    RuntimePolicyContext,
    SelfLearningPolicy,
    SelfLearningPolicyCompiler,
    ThresholdOverride,
)
from carnot.pipeline.semantic_grounding import (
    PromptClause,
    QuestionProfile,
    SemanticClaim,
    SemanticGroundingResult,
    SemanticGroundingVerifier,
    SemanticGroundingViolation,
    verify_semantic_grounding,
)
from carnot.pipeline.semantic_verifier_v2 import (
    SemanticClaimResult,
    SemanticVerifierV2,
    SemanticVerifierV2Result,
    SemanticVerifierV2Thresholds,
    verify_semantic_verifier_v2,
)
from carnot.pipeline.structured_reasoning import (
    StructuredReasoningAttempt,
    StructuredReasoningController,
    StructuredReasoningEmission,
    build_gemma_structured_reasoning_prompt,
    build_qwen_structured_reasoning_prompt,
    load_monitorability_policy,
)
from carnot.pipeline.typed_reasoning import (
    AtomicClaim,
    ExtractionProvenance,
    FinalAnswer,
    ReasoningStep,
    TypedReasoningExtractor,
    TypedReasoningIR,
    UserConstraint,
    extract_typed_reasoning,
)
from carnot.pipeline.verify_repair import (
    RepairResult,
    VerificationResult,
    VerifyRepairPipeline,
)
from carnot.pipeline.semantic_energy_extractor import (
    DualEnergyGate,
    DualEnergyResult,
    SemanticEnergyExtractor,
    SemanticEnergyResult,
    compute_semantic_energy,
)
from carnot.pipeline.prefill_uncertainty_probe import (
    PrefillUncertaintyProbe,
    PrefillUncertaintyResult,
    compute_conjugate_bound,
    compute_input_uncertainty,
    compute_prompt_uncertainty,
)
from carnot.pipeline.spilled_energy_extractor import (
    SpilledEnergyExtractor,
    SpilledEnergyResult,
    compute_lookahead_energy,
    compute_spilled_energy,
)
from carnot.pipeline.z3_extractor import Z3ArithmeticExtractor
from carnot.pipeline.jepa_fast_path import JepaGate
from carnot.pipeline.nl2z3_extractor import NL2Z3Extractor, Z3Result
from carnot.pipeline.z3_gated_repair import Z3GatedRepair, Z3GatedRepairResult, compute_skip_rate
from carnot.pipeline.dual_gpu_monitor import DualGPUMonitor, GPUProcessInfo
from carnot.pipeline.confidence_weighted_repair import (
    ConfidenceRepairResult,
    ConfidenceWeightedRepair,
    ViolationConfidence,
    compute_energy_variance_confidence,
    compute_expression_confidence,
)
from carnot.pipeline.adaptive_thresholds import (
    ModelAdaptiveThresholds,
    PerModelFPTracker,
    SelectiveConsolidation,
)
from carnot.pipeline.verge_refiner import (
    VergeIteration,
    VergeRefiner,
    build_step_repair_prompt,
    extract_failed_assertion,
)

__all__ = [
    "AgentStep",
    "ArithmeticExtractor",
    "AtomicClaim",
    "AutoExtractor",
    "CarnotError",
    "CaseEntry",
    "CaseKey",
    "CaseMatch",
    "CaseMemory",
    "CaseProvenance",
    "CaseQuery",
    "CaseRecord",
    "ConstraintMemory",
    "ConstraintState",
    "CodeVerificationTrace",
    "CodeExtractor",
    "LearningCurvePoint",
    "LearningImprovement",
    "ConstraintExtractor",
    "ConstraintResult",
    "ExtractionError",
    "ExtractionProvenance",
    "FactStatus",
    "FailureAnalyzer",
    "FailureReport",
    "FalseNegative",
    "FinalAnswer",
    "LogicExtractor",
    "LLMConstraintExtractor",
    "ModelLoadError",
    "NLExtractor",
    "PATTERN_THRESHOLD",
    "PrefillUncertaintyProbe",
    "PrefillUncertaintyResult",
    "PBTCodeVerificationResult",
    "PBTCodeVerifier",
    "PBTDerivedProperty",
    "PBTPropertyFailure",
    "PipelineTimeoutError",
    "PolicyProvenance",
    "PolicyQuery",
    "ProblemTypeScore",
    "PropertyBudgetUpdate",
    "PropertyFailureTrace",
    "PropertyRanker",
    "PropertyScore",
    "PromptClause",
    "PropertyCodeVerificationResult",
    "PropertyCodeVerifier",
    "PropertyFailure",
    "RepairPromptPatch",
    "DerivedProperty",
    "QuestionProfile",
    "RepairError",
    "RepairResult",
    "ReasoningStep",
    "RepairStrategy",
    "RoutingHint",
    "RuntimePolicyContext",
    "SemanticClaim",
    "SemanticClaimResult",
    "SemanticGroundingResult",
    "SemanticGroundingVerifier",
    "SemanticGroundingViolation",
    "SemanticVerifierV2",
    "SemanticVerifierV2Result",
    "SemanticVerifierV2Thresholds",
    "StrategyRecommendation",
    "StructuredReasoningAttempt",
    "StructuredReasoningController",
    "StructuredReasoningEmission",
    "TraceAnalysis",
    "TraceAnalyzer",
    "TrackedFact",
    "ThresholdOverride",
    "TypedReasoningExtractor",
    "TypedReasoningIR",
    "UserConstraint",
    "VerificationError",
    "VerificationResult",
    "VerificationTraceStep",
    "VerifyRepairPipeline",
    "SelfLearningPolicy",
    "SelfLearningPolicyCompiler",
    "DualEnergyGate",
    "DualEnergyResult",
    "SemanticEnergyExtractor",
    "SemanticEnergyResult",
    "SpilledEnergyExtractor",
    "SpilledEnergyResult",
    "Z3ArithmeticExtractor",
    "Z3GatedRepair",
    "Z3GatedRepairResult",
    "Z3Result",
    "JepaGate",
    "NL2Z3Extractor",
    "compute_skip_rate",
    "ConfidenceRepairResult",
    "ConfidenceWeightedRepair",
    "ViolationConfidence",
    "compute_energy_variance_confidence",
    "compute_expression_confidence",
    "DualGPUMonitor",
    "GPUProcessInfo",
    "ModelAdaptiveThresholds",
    "PerModelFPTracker",
    "SelectiveConsolidation",
    "VergeIteration",
    "VergeRefiner",
    "build_step_repair_prompt",
    "extract_failed_assertion",
    "compute_conjugate_bound",
    "compute_input_uncertainty",
    "compute_lookahead_energy",
    "compute_prompt_uncertainty",
    "compute_semantic_energy",
    "compute_spilled_energy",
    "extract_typed_reasoning",
    "propagate",
    "build_gemma_structured_reasoning_prompt",
    "build_qwen_structured_reasoning_prompt",
    "extract_official_test_examples",
    "extract_prompt_examples",
    "load_monitorability_policy",
    "verify_semantic_grounding",
    "verify_semantic_verifier_v2",
    "verify_code",
]
