"""DraftConditionedVerifier — Tier 2.8: draft-scaffolded structural constraint injection.

**Researcher summary:**
    Inspired by arXiv 2603.03305 (Draft-Conditioned Constrained Decoding), this module
    generates a cheap 50-token draft answer from a small model (e.g. Qwen3.5-0.8B),
    extracts structural markers from that draft (does it contain an equals sign? a numeric
    answer? multiple reasoning steps?), and injects those markers as soft constraints into
    the Tier 3 Ising energy function.

    The draft does NOT need to be correct.  Its value lies in its STRUCTURE: a draft that
    contains "=" and a final number tells the Ising sampler "this question type expects
    numeric equality reasoning."  That prior narrows the search space and reduces the
    constraint violation rate for the full response.

    Positioned between Tier 2 (EORM/JEPA energy) and Tier 3 (Ising constraint check).

**Why structural constraints instead of semantic ones?**
    The ArithmeticExtractor (python/carnot/verify/arithmetic_extractor.py) has been shown
    to produce inconsistent results when the response format deviates from expected patterns
    (see Exp 800 post-mortem, label "BROKEN" in the codebase).  Structural pattern matching
    is deterministic and never fails silently — "=" is either present or not.

**How the Ising scoring works:**
    `score_with_constraints()` converts structural constraints to a scalar energy by
    summing penalty signals.  Each active constraint adjusts a base energy: the sign is
    chosen so that a CONSISTENT response (one whose structure matches the draft) has LOWER
    energy than an inconsistent one.  Energy is then passed back to the caller unchanged
    in the VerificationResult.

    When `ising_sampler` is None (CI mode or unit tests), the method computes a purely
    synthetic energy from the structural signals alone — no external model required.

Spec: REQ-TIER28-001, SCENARIO-TIER28-001
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Any


# ---------------------------------------------------------------------------
# VerificationResult
# ---------------------------------------------------------------------------


@dataclass
class VerificationResult:
    """Result of a single DraftConditionedVerifier.verify_with_draft() call.

    Attributes:
        energy: Scalar Ising energy for the full response, with draft-injected
            structural constraints applied.  Lower energy means the response is
            more consistent with the structural priors derived from the draft.
        draft_used: True when a draft was generated and structural constraints
            were extracted from it.  False when draft generation failed or was
            skipped (energy is then the raw Ising score with no injection).
        n_constraints: Number of structural constraints that were active (True)
            for this draft.  Zero means the draft had no structural signal.
        draft_text: The raw draft text generated by draft_runner.  Empty string
            when draft generation failed or was skipped.
        constraints: The full list of constraint dicts as returned by
            extract_structural_constraints().  Empty list when draft_used=False.

    Spec: REQ-TIER28-001
    """

    energy: float
    draft_used: bool
    n_constraints: int
    draft_text: str = ""
    constraints: list[dict[str, Any]] = None  # type: ignore[assignment]

    def __post_init__(self) -> None:
        if self.constraints is None:
            self.constraints = []


# ---------------------------------------------------------------------------
# DraftConditionedVerifier
# ---------------------------------------------------------------------------


class DraftConditionedVerifier:
    """Tier 2.8: generate a cheap draft, extract structural constraints, score full response.

    **How to use:**

        >>> verifier = DraftConditionedVerifier(draft_runner=my_runner, ising_sampler=my_ising)
        >>> result = verifier.verify_with_draft(question, full_response)
        >>> print(result.energy, result.n_constraints)

    **What "draft_runner" must implement:**

        Any object with a callable interface
        ``generate(question: str, max_tokens: int) -> str``.
        The returned string is the raw text completion.  Empty string or any
        exception is silently treated as "draft unavailable" (energy falls back
        to raw Ising score).

    **What "ising_sampler" must implement:**

        Any object with
        ``score_with_constraints(response: str, constraints: list[dict]) -> float``.
        When ``ising_sampler`` is None (CI mode / unit tests), a synthetic energy
        is computed from the structural constraint signals only — no external model.

    Parameters
    ----------
    draft_runner :
        Small-model inference object.  Must have `.generate(question, max_tokens)`.
    ising_sampler :
        Ising sampler used for Tier 3 scoring.  May be None for CI/test runs.
    max_draft_tokens : int
        Maximum tokens to generate for the draft.  Default 50 is enough to see
        the structural shape without wasting time on a full answer.

    Spec: REQ-TIER28-001
    """

    def __init__(
        self,
        draft_runner: Any,
        ising_sampler: Any | None = None,
        max_draft_tokens: int = 50,
    ) -> None:
        self.draft_runner = draft_runner
        self.ising = ising_sampler
        self.max_draft_tokens = max_draft_tokens

    # ------------------------------------------------------------------
    # extract_structural_constraints
    # ------------------------------------------------------------------

    def extract_structural_constraints(self, draft_text: str) -> list[dict[str, Any]]:
        """Extract structural markers from a draft response without ArithmeticExtractor.

        Uses deterministic pattern matching only — no model inference, no parser.
        Each constraint is a dict with "type" (str) and "value" (bool | int | None).
        Only constraints where `value` is truthy (or a non-None int) are considered
        "active" in the energy computation.

        Structural markers extracted:
            has_equals_sign:
                True when the draft contains "=".  Signals that the question expects
                an equation-style answer (arithmetic, algebra, unit conversion).
            has_numeric_answer:
                True when the last 100 characters of the draft contain at least one
                standalone integer.  Signals that the response should end with a number.
            has_reasoning_steps:
                True when the draft has more than 3 newline-delimited lines.  Signals
                that multi-step CoT is expected (not a one-liner).
            final_number:
                The last integer found anywhere in the draft, or None if no digits.
                Provides a weak anchor for the expected magnitude of the answer.

        Args:
            draft_text: Raw text from the draft runner (may be empty).

        Returns:
            List of dicts, each with keys "type" (str) and "value" (bool | int | None).

        Spec: REQ-TIER28-001
        """
        constraints: list[dict[str, Any]] = []

        # Constraint 1: equality sign present in draft.
        # Why: arithmetic word problems almost always require writing "a + b = c".
        # A draft that contains "=" signals to the Ising sampler: penalise responses
        # that have no equality relation.
        has_eq = "=" in draft_text
        constraints.append({"type": "has_equals_sign", "value": has_eq})

        # Constraint 2: numeric token in the last 100 characters.
        # Why: the tail of a draft response is where the final answer appears.
        # If the draft ends with a number, the full response is also expected to.
        tail = draft_text[-100:] if len(draft_text) > 100 else draft_text
        has_num = re.search(r"\b\d+\b", tail) is not None
        constraints.append({"type": "has_numeric_answer", "value": has_num})

        # Constraint 3: multi-line reasoning (proxy for CoT step count).
        # Why: arXiv 2603.03305 shows that structural depth correlates with answer
        # correctness on math benchmarks.  More newlines = more reasoning steps.
        n_lines = len(draft_text.split("\n"))
        has_steps = n_lines > 3
        constraints.append({"type": "has_reasoning_steps", "value": has_steps})

        # Constraint 4: last integer in the entire draft — magnitude anchor.
        # Why: the Ising energy function uses this as a soft prior; a full response
        # whose final number is very far from this anchor gets a higher energy penalty.
        # Returns None (inactive) when the draft contains no digits.
        all_digits = re.findall(r"\b\d+\b", draft_text)
        final_num: int | None = int(all_digits[-1]) if all_digits else None
        constraints.append({"type": "final_number", "value": final_num})

        return constraints

    # ------------------------------------------------------------------
    # score_with_constraints
    # ------------------------------------------------------------------

    def score_with_constraints(
        self, response: str, constraints: list[dict[str, Any]]
    ) -> float:
        """Score a full response using Ising energy + structural constraint signals.

        If ``self.ising`` is set, delegates to ``ising.score_with_constraints()``.
        Otherwise computes a purely synthetic energy from the constraint signals:

            energy = base_energy
                     - 0.1 * has_equals_sign_active
                     - 0.1 * has_numeric_answer_active
                     - 0.05 * has_reasoning_steps_active
                     + magnitude_penalty_if_final_number_present

        Lower energy = more consistent with draft structural priors.

        Args:
            response:    Full LLM response text to score.
            constraints: Output of extract_structural_constraints().

        Returns:
            Scalar energy float.

        Spec: REQ-TIER28-001
        """
        if self.ising is not None:
            try:
                return float(self.ising.score_with_constraints(response, constraints))
            except Exception:
                # Fall through to synthetic computation on any failure.
                pass

        # Synthetic energy for CI / test runs.
        # Base energy: use response length as a rough proxy for "effort".
        # Longer, multi-step responses should have lower base energy.
        base = 1.0 - min(len(response) / 500.0, 0.5)  # range [0.5, 1.0]

        # Build a quick lookup for constraint values.
        cmap: dict[str, Any] = {c["type"]: c["value"] for c in constraints}

        # Active structural signals lower the energy (reward consistency).
        if cmap.get("has_equals_sign"):
            base -= 0.1
        if cmap.get("has_numeric_answer"):
            base -= 0.1
        if cmap.get("has_reasoning_steps"):
            base -= 0.05

        # Magnitude anchor: if a final_number was extracted from the draft, check
        # whether the response also ends with a number in a similar magnitude.
        draft_final = cmap.get("final_number")
        if draft_final is not None and draft_final > 0:
            resp_digits = re.findall(r"\b\d+\b", response)
            if resp_digits:
                resp_final = int(resp_digits[-1])
                # Penalise when the response final number differs by more than 10×.
                ratio = max(resp_final, draft_final) / max(min(resp_final, draft_final), 1)
                if ratio > 10.0:
                    base += 0.15  # penalty for wildly wrong magnitude

        return base

    # ------------------------------------------------------------------
    # verify_with_draft
    # ------------------------------------------------------------------

    def verify_with_draft(
        self, question: str, full_response: str
    ) -> VerificationResult:
        """Run full Tier 2.8 verification: draft → constraints → constrained Ising score.

        Steps:
            1. Generate a cheap draft (up to max_draft_tokens) with draft_runner.
            2. Extract structural constraints from the draft text.
            3. Score full_response against those constraints via score_with_constraints().
            4. Return a VerificationResult with energy, draft metadata, and constraints.

        When draft generation raises an exception or returns an empty string,
        draft_used is set to False and the response is scored with an empty
        constraints list (falling through to raw Ising or synthetic energy).

        Args:
            question:      The original question text.
            full_response: The full LLM response to score.

        Returns:
            VerificationResult dataclass.

        Spec: REQ-TIER28-001
        """
        draft_text = ""
        draft_used = False
        constraints: list[dict[str, Any]] = []

        # Step 1: generate draft.
        try:
            raw = self.draft_runner.generate(question, self.max_draft_tokens)
            if raw:
                draft_text = str(raw)
                draft_used = True
        except Exception:
            # Draft failure is non-fatal — gracefully fall back to no-draft scoring.
            draft_text = ""
            draft_used = False

        # Step 2: extract structural constraints from draft (empty list when no draft).
        if draft_used:
            constraints = self.extract_structural_constraints(draft_text)

        # Count active constraints (truthy values, or non-None integers).
        n_active = sum(
            1
            for c in constraints
            if c["value"] is not None and c["value"] is not False and c["value"] != ""
        )

        # Step 3: score the full response with the constraints.
        energy = self.score_with_constraints(full_response, constraints)

        return VerificationResult(
            energy=energy,
            draft_used=draft_used,
            n_constraints=n_active,
            draft_text=draft_text,
            constraints=constraints,
        )

    # ------------------------------------------------------------------
    # condition_and_verify  (ThreeTierPipeline wire_tier_28 interface)
    # ------------------------------------------------------------------

    def condition_and_verify(
        self, question: str, full_response: str
    ) -> dict[str, Any]:
        """Tier 2.8 interface expected by ThreeTierPipeline.wire_tier_28().

        Wraps verify_with_draft() and returns the result as a plain dict so that
        ThreeTierPipeline does not need to import VerificationResult directly.
        The dict is stored in pipeline._last_tier28_advisory.

        Args:
            question:      The original question text.
            full_response: The LLM response to evaluate.

        Returns:
            Dict with keys: energy, draft_used, n_constraints, draft_text, constraints.

        Spec: REQ-TIER28-001
        """
        result = self.verify_with_draft(question, full_response)
        return {
            "energy": result.energy,
            "draft_used": result.draft_used,
            "n_constraints": result.n_constraints,
            "draft_text": result.draft_text,
            "constraints": result.constraints,
        }
