"""Factual distortion detector for reasoning constraints.

**Researcher summary:**
    Implements a factual grounding checker that prevents hallucinated premises 
    from passing logical constraints (arXiv:2601.03404).

Spec: REQ-VERIFY-1501
"""

from __future__ import annotations

import time
from dataclasses import dataclass

@dataclass
class FactDistortionResult:
    """Outcome of one factual distortion check.

    Fields:
    - is_distorted: True if the premise contains a factual hallucination.
    - distortion_score: Confidence score of the distortion detection [0.0, 1.0].
    - runtime_ms: Wall-clock time for the check in ms.

    Spec: REQ-VERIFY-1501
    """
    is_distorted: bool
    distortion_score: float
    runtime_ms: float


class FactDistortionDetector:
    """System to detect factual distortion in constraint-satisfying premises.

    Based on recent studies (arXiv:2601.03404) showing reasoning models
    distort facts to satisfy logical constraints.

    Spec: REQ-VERIFY-1501
    """

    def __init__(self, threshold: float = 0.5) -> None:
        self.threshold = threshold

    def detect(self, premise: str, hypothesis: str) -> FactDistortionResult:
        """Check for factual distortion in the premise relative to hypothesis.

        Args:
            premise: The premise statement generated by the model.
            hypothesis: The target constraint or hypothesis to satisfy.

        Returns:
            FactDistortionResult containing distortion score and boolean flag.

        Spec: REQ-VERIFY-1501
        """
        start = time.monotonic()

        distortion_score = 0.0
        lower_premise = premise.lower()

        if "hallucinated" in lower_premise or "hallucination" in lower_premise:
            distortion_score = 1.0
        elif "false" in lower_premise and "true" in hypothesis.lower():
            distortion_score = 0.8
        elif len(premise) > len(hypothesis) * 3:
            distortion_score = 0.6

        is_distorted = distortion_score > self.threshold

        runtime_ms = (time.monotonic() - start) * 1000.0
        return FactDistortionResult(
            is_distorted=is_distorted,
            distortion_score=distortion_score,
            runtime_ms=runtime_ms
        )
