"""FOVER-to-EORM data pipeline: load FOVER-labeled steps and convert for EORM/JEPA retrain.

**Researcher summary:**
    RETRO-024 has been open for 6 consecutive milestones because all EORM/JEPA retrains
    ran on synthetic data only.  Exp 430 produced the missing ingredient: real (step_text,
    label) pairs generated by running LLM CoT responses through the FOVERAnnotator Z3
    pipeline.  This module provides the three functions that bridge Exp 430 output to
    Exp 431 EORM/JEPA retrain input.

**Why these three functions and not one monolithic pipeline?**
    Separating load, conversion, and verdict into independent functions makes each
    individually testable to 100% coverage.  The experiment script composes them in
    sequence, but CI can unit-test each in isolation with synthetic JSON fixtures.

**Data flow:**
    results/fover_labeled_steps.json
        └─> load_fover_pairs()          # filter by confidence and label
            └─> fover_pairs_to_contrastive()  # group by question_id, build (pos, neg) tensors
                └─> EORMTrainer.train_epoch(triples)  # EORM contrastive training
    results/fover_labeled_steps.json
        └─> load_fover_pairs()
            └─> ViolationPair list for JEPARetrainer.train_epoch()

Spec: REQ-LEARN-032, REQ-LEARN-033,
      SCENARIO-LEARN-057, SCENARIO-LEARN-058, SCENARIO-LEARN-059
"""

from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path

import jax.numpy as jnp


# ---------------------------------------------------------------------------
# load_fover_pairs
# ---------------------------------------------------------------------------


def load_fover_pairs(path: str) -> list[dict]:
    """Load FOVER-labeled steps from a JSON file, filtering by label and confidence.

    **Detailed explanation for engineers:**
        The FOVER labeled steps file (results/fover_labeled_steps.json) is produced
        by FOVERAnnotator.to_training_pairs() (Exp 430).  Each pair has four fields:
        - question_id (str): identifies which question produced this step
        - step_text (str): the raw CoT step text
        - label (str): 'correct' | 'incorrect' | 'not_verifiable'
        - confidence (float): Z3 match confidence in [0.0, 1.0]

        Filtering rules (from REQ-LEARN-031 and REQ-LEARN-032):
        1. Only include pairs with label in ('correct', 'incorrect').
           Steps labeled 'not_verifiable' provide no learning signal — the Z3 solver
           could not determine correctness, so there is no ground-truth label to train on.
        2. Only include pairs with confidence >= 0.3.
           Confidence < 0.3 indicates a partial regex match (ambiguous equation extraction).
           Training on ambiguous labels adds noise that degrades EORM precision.

        The JSON file may use either the schema produced by Exp 430:
        - Top-level 'pairs' list (schema carnot.fover_labels.v1)
        - OR a bare top-level list (for forward compatibility with future schema)

        Missing file, malformed JSON, wrong structure: all return empty list rather
        than raising, so the experiment script can detect < 10 real pairs and fall back
        to synthetic data without crashing.

    Args:
        path: Path to the FOVER labeled steps JSON file
              (typically results/fover_labeled_steps.json).

    Returns:
        List of dicts, each with keys: question_id, step_text, label, confidence.
        Only pairs with label in ('correct', 'incorrect') and confidence >= 0.3
        are included.  May be empty if no qualifying pairs exist.

    Spec: REQ-LEARN-032, SCENARIO-LEARN-057
    """
    try:
        p = Path(path)
        if not p.exists():
            return []
        with open(p) as f:
            data = json.load(f)
    except (OSError, json.JSONDecodeError):
        return []

    # Support schema carnot.fover_labels.v1 (top-level 'pairs' key) or bare list
    if isinstance(data, dict):
        raw_pairs = data.get("pairs", [])
    elif isinstance(data, list):
        raw_pairs = data
    else:
        return []

    if not isinstance(raw_pairs, list):
        return []

    result: list[dict] = []
    for entry in raw_pairs:
        if not isinstance(entry, dict):
            continue
        label = entry.get("label", "")
        confidence = float(entry.get("confidence", 0.0))
        if label not in ("correct", "incorrect"):
            continue
        if confidence < 0.3:
            continue
        result.append(
            {
                "question_id": str(entry.get("question_id", "unknown")),
                "step_text": str(entry.get("step_text", "")),
                "label": label,
                "confidence": confidence,
            }
        )

    return result


# ---------------------------------------------------------------------------
# fover_pairs_to_contrastive
# ---------------------------------------------------------------------------


def fover_pairs_to_contrastive(
    pairs: list[dict],
) -> list[tuple[jnp.ndarray, jnp.ndarray]]:
    """Convert FOVER pairs into (positive, negative) embedding tuples for EORM training.

    **Detailed explanation for engineers:**
        EORM trains with a contrastive (hinge) loss that requires PAIRS of responses
        for the same question: one correct (positive, lower energy) and one incorrect
        (negative, higher energy).  The FOVER pairs carry individual (step_text, label)
        entries rather than explicit pairs.

        This function groups pairs by question_id and round-robin matches each
        correct step against each incorrect step for the same question.  Steps from
        different questions are never matched — that would create false contrastive
        signal (the model would be penalized for preferring a correct step from
        question A over an incorrect step from question B).

        Special handling for shared buckets:
        - question_id == 'unknown' and question_id.startswith('synthetic_') both
          route to a shared pool so that synthetic fallback data can form contrastive
          pairs despite every pair having a distinct question_id.

        Text-to-embedding:
        - Each step_text is converted to a 64-dimensional embedding using a simple
          character-code mean-pool with sinusoidal projection.  This is the same
          approach used by JEPARetrainer._text_to_embedding, keeping EORM and JEPA
          embeddings in the same space.
        - embed_dim=64 matches the default JEPAEnergyConfig.

        Returns only pairs where BOTH correct and incorrect steps exist for the same
        question.  Questions with only one label type produce no contrastive pairs.

    Args:
        pairs: List of FOVER pair dicts (from load_fover_pairs).
               Each dict has: question_id, step_text, label, confidence.

    Returns:
        List of (positive_emb, negative_emb) tuples where each element is a
        jnp.ndarray of shape (64,).  Positive = correct step embedding;
        Negative = incorrect step embedding.

    Spec: REQ-LEARN-032, SCENARIO-LEARN-058
    """
    import math  # local import: only needed here, avoids module-level overhead

    def _text_to_embedding(text: str, embed_dim: int = 64) -> jnp.ndarray:
        """Embed step text as character-code mean-pool with sinusoidal projection.

        Same algorithm as jepa_retrain._text_to_embedding.  Kept local to avoid
        circular imports (jepa_retrain imports from jepa_energy, which is heavy).
        """
        if not text:
            return jnp.zeros(embed_dim)
        words = text.split()
        word_scalars: list[float] = [
            sum(ord(c) for c in w) / (len(w) * 128.0) for w in words
        ]
        mean_val = sum(word_scalars) / len(word_scalars)
        dims = jnp.arange(embed_dim, dtype=jnp.float32)
        freqs = (dims + 1.0) * math.pi / embed_dim
        return jnp.where(dims % 2 == 0, jnp.cos(freqs * mean_val), jnp.sin(freqs * mean_val))

    # Group correct/incorrect step texts by question_id
    _SHARED_POOL = "_synthetic_pool"
    correct_by_q: dict[str, list[str]] = defaultdict(list)
    incorrect_by_q: dict[str, list[str]] = defaultdict(list)

    for p in pairs:
        q_id = p["question_id"]
        if q_id == "unknown" or q_id.startswith("synthetic_"):
            key = _SHARED_POOL
        else:
            key = q_id

        if p["label"] == "correct":
            correct_by_q[key].append(p["step_text"])
        else:
            incorrect_by_q[key].append(p["step_text"])

    all_keys = set(correct_by_q.keys()) | set(incorrect_by_q.keys())
    result: list[tuple[jnp.ndarray, jnp.ndarray]] = []

    for key in sorted(all_keys):
        corrects = correct_by_q.get(key, [])
        incorrects = incorrect_by_q.get(key, [])

        if not corrects or not incorrects:
            continue

        # Round-robin pairing: avoids O(n^2) explosion for large question groups
        n_pairs = max(len(corrects), len(incorrects))
        for i in range(n_pairs):
            pos_text = corrects[i % len(corrects)]
            neg_text = incorrects[i % len(incorrects)]
            pos_emb = _text_to_embedding(pos_text)
            neg_emb = _text_to_embedding(neg_text)
            result.append((pos_emb, neg_emb))

    return result


# ---------------------------------------------------------------------------
# compute_retrain_verdict
# ---------------------------------------------------------------------------


def compute_retrain_verdict(
    before_auc: float,
    after_auc: float,
    n_real_pairs: int,
) -> str:
    """Determine the honest verdict for an EORM/JEPA retrain experiment.

    **Detailed explanation for engineers:**
        The verdict string is the key field that determines whether RETRO-024 is
        closed.  Three mutually exclusive outcomes:

        'real_data_improvement':
            after_auc > before_auc AND n_real_pairs >= 10.
            This is the only outcome that constitutes genuine evidence of real-world
            improvement.  AUC > 0.5 on real pairs means the model has learned
            something beyond random chance from real LLM-generated data.

        'synthetic_only':
            n_real_pairs < 10 regardless of AUC values.
            Fewer than 10 real pairs is insufficient for a meaningful retrain.
            We fall back to synthetic data; the AUC may improve but that improvement
            reflects synthetic corpus quality, not real-world performance.
            The threshold of 10 is intentionally conservative: 10 pairs gives at most
            5 contrastive triples (5 correct + 5 incorrect per question, best case),
            which is barely enough for one gradient step.

        'real_data_no_improvement':
            n_real_pairs >= 10 AND after_auc <= before_auc.
            Real data was available but the retrain did not improve AUC.  This honest
            negative result is logged for future analysis (more data? lower LR? more
            epochs?).  It does NOT close RETRO-024 — the problem remains open.

    Args:
        before_auc: AUC-ROC on held-out test set before retraining.
        after_auc: AUC-ROC on held-out test set after retraining.
        n_real_pairs: Number of real FOVER-labeled pairs used for training.

    Returns:
        One of: 'real_data_improvement', 'synthetic_only', 'real_data_no_improvement'.

    Spec: REQ-LEARN-032, SCENARIO-LEARN-059
    """
    if n_real_pairs < 10:
        return "synthetic_only"
    if after_auc > before_auc:
        return "real_data_improvement"
    return "real_data_no_improvement"
