"""HermesV2LiveLoop — step-by-step live generation with mid-generation verification.

**Why this module exists (RETRO-070):**

    Exp 629 (InterWhen) and Exp 633 (HermesVerifierAdapter) both achieved
    recall=0.12 on the live_pairs_578 corpus.  The ceiling is 12% because
    IT-tuned models (Qwen3.5-0.8B, Gemma-4) express explicit arithmetic in
    only ~12% of their prose sentences.  Post-hoc verification cannot detect
    what was never written.

    The fix: generate step-by-step LIVE.  Prompt the model for one sentence at
    a time.  After each sentence, run SymCodeVerifier.detection_score().  If a
    violation is detected, inject a correction hint into the generation context
    BEFORE the next sentence is generated.  The verifier sees "47 apples...
    28 oranges... total of 76" AS the model writes it, not after the complete
    response is committed.

    This is architecturally different from post-hoc monitoring:
      - Post-hoc: full response → segment → verify → score  (ceiling: 12%)
      - Live loop: partial context → generate 1 sentence → verify → inject hint
        → generate next sentence → ...  (target: >= 0.20, gate target: >= 0.30)

    The architecture follows the HERMES paper (arXiv 2511.18760) but adapts it
    to sentence-level generation rather than full-step-at-once generation.

Spec: REQ-VERIFY-137, REQ-VERIFY-138,
      SCENARIO-VERIFY-180, SCENARIO-VERIFY-181, SCENARIO-VERIFY-182
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Callable, Optional

from carnot.pipeline.symcode_verifier import SymCodeVerifier


# ---------------------------------------------------------------------------
# HermesV2StepResult — result of one sentence in the live generation loop
# ---------------------------------------------------------------------------


@dataclass
class HermesV2StepResult:
    """Result of one sentence step in the HermesV2 live generation loop.

    Each step is one sentence generated by the LLM.  After generation,
    SymCodeVerifier is run on the sentence text in isolation to check for
    arithmetic violations.  If a violation is found, a correction hint is
    injected into the context before the next sentence is generated.

    Fields:
        step_index         — Zero-based sentence index within this response.
        step_text          — The sentence generated by the LLM (or stub).
        violation_detected — True iff SymCodeVerifier.detection_score > 0.0.
        detection_score    — Raw SymCodeVerifier score for this sentence alone.
                             0.0 means no arithmetic violation detected.
        hint_injected      — True iff a correction hint was appended to the
                             context before the next sentence was generated.
        hint_text          — The hint string, or None if no hint was injected.
                             Non-None iff hint_injected=True.
    """

    step_index: int
    step_text: str
    violation_detected: bool
    detection_score: float
    hint_injected: bool
    hint_text: Optional[str]


# ---------------------------------------------------------------------------
# HermesV2GenerationResult — full result for one question
# ---------------------------------------------------------------------------


@dataclass
class HermesV2GenerationResult:
    """Complete result of running HermesV2LiveLoop on one question.

    Contains the full generated response (all sentences joined) and a
    per-sentence step record so callers can inspect exactly where violations
    were detected and where hints were injected.

    Fields:
        question        — The original question text.
        full_response   — All generated sentences joined with spaces.
        step_results    — Ordered list of HermesV2StepResult, one per sentence.
        any_violation   — True iff at least one step had violation_detected=True.
        n_violations    — Total count of steps with violation_detected=True.
        n_hints         — Total count of steps where hint_injected=True.
                          In the current implementation n_hints == n_violations,
                          but they are tracked separately so future policies
                          can suppress some hints (e.g. low-confidence hints).
    """

    question: str
    full_response: str
    step_results: list[HermesV2StepResult] = field(default_factory=list)
    any_violation: bool = False
    n_violations: int = 0
    n_hints: int = 0


# ---------------------------------------------------------------------------
# HermesV2LiveLoop — the live generation + verification loop
# ---------------------------------------------------------------------------

# Regex to extract the first sentence from a multi-sentence LLM response.
# Split on sentence-ending punctuation optionally followed by whitespace/newline.
_SENTENCE_SPLIT_RE = re.compile(r"(?<=[.!?])\s+|(?<=[.!?])$|\n")


class HermesV2LiveLoop:
    """Generate answers one sentence at a time, verifying arithmetic at each boundary.

    This class implements the live mid-generation verification loop from RETRO-070.
    Instead of generating a complete response and then post-hoc verifying it
    (which misses ~88% of violations because IT models rarely write explicit
    arithmetic), HermesV2LiveLoop:

        1. Generates one sentence from the LLM given the accumulated context.
        2. Runs SymCodeVerifier.detection_score() on the new sentence.
        3. If a violation is detected (score > 0.0): appends a correction hint
           to the generation context before the next sentence.
        4. Repeats for up to max_sentences sentences or until no new text is
           generated.

    The correction hint ("Re-check the previous arithmetic step.") primes the
    model to self-correct on the NEXT sentence rather than compounding the error.

    In CI mode (llm_caller=None): _generate_step() returns an empty string,
    the loop exits on the first step, and all detection scores are 0.0.  This
    allows the full pipeline to be tested without a live GPU.

    Args:
        llm_caller           : callable(prompt: str) -> str, or None for CI stub.
                               In live mode, pass a Qwen3.5-0.8B pipeline function.
        verifier             : SymCodeVerifier instance for mid-step checking.
        max_sentences        : Maximum sentences to generate per question.
                               Prevents infinite loops on verbose models.
        max_new_tokens_per_step : Soft guidance token budget per sentence.
                               Passed as context to the prompt string; the
                               actual LLM call respects only the prompt.

    Spec: REQ-VERIFY-137
    """

    # The hint injected when a violation is detected mid-generation.
    # Deliberately short and non-domain-specific so it works for any arithmetic type.
    CORRECTION_HINT = "[Note: Recheck the previous arithmetic step carefully.]"

    def __init__(
        self,
        llm_caller: Optional[Callable[[str], str]],
        verifier: SymCodeVerifier,
        max_sentences: int = 10,
        max_new_tokens_per_step: int = 80,
    ) -> None:
        self.llm_caller = llm_caller
        self.verifier = verifier
        self.max_sentences = max_sentences
        self.max_new_tokens = max_new_tokens_per_step

    # ------------------------------------------------------------------
    # Internal: generate one sentence
    # ------------------------------------------------------------------

    def _generate_step(self, context: str) -> str:
        """Generate one sentence from the LLM given the accumulated context.

        Why "one sentence only" in the prompt: we need to run the verifier after
        EACH sentence boundary.  Asking for one sentence at a time enforces the
        boundary rather than relying on post-hoc splitting.

        If llm_caller is None (CI stub mode): returns an empty string so the
        loop exits immediately.  This lets tests exercise the pipeline logic
        without a GPU.

        The prompt appends " (Continue. Write one sentence only.)" so even
        instruction-tuned models that echo the question will at least produce
        a short output.  The first non-empty sentence extracted from the
        response is returned.

        Args:
            context: Full accumulated generation context so far, including the
                     question prefix, all previously generated sentences, and
                     any correction hints.

        Returns:
            A single sentence string (may be empty if the LLM returns nothing).
        """
        if self.llm_caller is None:
            # CI stub: return empty to terminate the loop immediately.
            return ""

        prompt = context + " (Continue. Write one sentence only.)"
        try:
            response = self.llm_caller(prompt)
        except Exception:  # noqa: BLE001 — LLM errors are non-fatal
            return ""

        if not response or not response.strip():
            return ""

        # Extract the first non-empty sentence from the response.
        # _SENTENCE_SPLIT_RE splits on sentence-ending punctuation or newlines.
        parts = _SENTENCE_SPLIT_RE.split(response.strip())
        for part in parts:
            stripped = part.strip()
            if stripped:
                return stripped

        # Fallback: return the whole stripped response if splitting yields nothing.
        return response.strip()

    # ------------------------------------------------------------------
    # Public: generate with verification
    # ------------------------------------------------------------------

    def generate_with_verification(self, question: str) -> HermesV2GenerationResult:
        """Generate a step-by-step answer, verifying arithmetic at each sentence boundary.

        This is the core of RETRO-070's fix.  By verifying at each sentence
        boundary (not after the full response), we can detect violations in
        responses that would otherwise score 0.0 under post-hoc monitoring —
        because the hint injected after a violation primes the model to write
        the corrected arithmetic in its NEXT sentence, producing verifiable
        arithmetic where post-hoc review would see only natural language.

        The loop runs for at most max_sentences iterations or until:
        - The LLM generates an empty sentence (natural stop).
        - The accumulated context exceeds 300 words (safety cap).

        Args:
            question: The question to answer.

        Returns:
            HermesV2GenerationResult with all fields populated.
        """
        context = f"Question: {question}\nAnswer:"
        steps: list[HermesV2StepResult] = []

        for i in range(self.max_sentences):
            sentence = self._generate_step(context)
            if not sentence.strip():
                # Natural stop: LLM returned empty or CI stub mode.
                break

            score = self.verifier.detection_score(sentence)
            violated = score > 0.0
            hint: Optional[str] = None
            hint_injected = False

            if violated:
                hint = self.CORRECTION_HINT
                hint_injected = True

            steps.append(
                HermesV2StepResult(
                    step_index=i,
                    step_text=sentence,
                    violation_detected=violated,
                    detection_score=score,
                    hint_injected=hint_injected,
                    hint_text=hint,
                )
            )

            # Append the new sentence and optional hint to the running context.
            context += " " + sentence
            if hint:
                context += " " + hint

            # Safety cap: stop if context is getting very long (300 word limit).
            # This prevents runaway generation on verbose models.
            if len(context.split()) > 300:
                break

        full_response = " ".join(s.step_text for s in steps)
        return HermesV2GenerationResult(
            question=question,
            full_response=full_response,
            step_results=steps,
            any_violation=any(s.violation_detected for s in steps),
            n_violations=sum(1 for s in steps if s.violation_detected),
            n_hints=sum(1 for s in steps if s.hint_injected),
        )
